export default {
    "empty_cart": "Commencez votre commande en ajoutant un produit à votre panier.",
    "view_range": "Voir l'assortiment",
    "subtotal": "Sous-total",
    "coupon_discount": "Réduction coupon",
    "group_discount": "Réduction de groupe",
    "redeem_discount": "Réduction carte de fidélité",
    "coupon_code": "Code promo",
    "apply_redeem_discount": "Cliquez ici pour appliquer votre réduction carte de fidélité",
    "apply_redeem_discount_desk": "Cliquez ici pour utiliser votre réduction carte de fidélité.",
    "total": "Total",
    "apply_coupon": "Appliquer",
    "comment": "Commentaires éventuels",
    "further": "Suivant",
    "step_overview": "Aperçu de la commande",
    "step_table_number": "Numéro de table",
    "step_confirmation": "Confirmation",
    "step_payment_method": "Mode de paiement",
    "product_added_success": "Produit ajouté au panier",
    "product_not_available": "Les produits marqués en rouge ne sont pas disponibles",
    "product_option_not_available": "Les produits et/ou options marqués en rouge ne sont pas disponibles",
    "message_invalid_coupon_product": "La réduction ne s'applique pas aux produits de votre panier.",
    "message_apply_coupon_successfully": "Code promo appliqué avec succès.",
    "message_apply_coupon_failed": "Veuillez d'abord ajouter un produit à votre panier.",
    "oops": "Oups",
    "product_impossible_contact_admin": "Il n'est pas possible d'ajouter des produits à votre panier. Veuillez contacter l'exploitant.",
    "back": "Retour",
    "delivery_free_from": "Livraison gratuite à partir de",
    "delivery_minimum": "{workspaceName} applique un montant minimum de commande de : {price} hors frais de livraison",
    "delivery_minimum-desk": "{workspaceName} applique un montant minimum de commande de : {price} hors frais de livraison",
    "delivery_costs": "Frais de livraison",
    "delivery_not_shipping_1": "{workspaceName} ne livre pas à cet emplacement.",
    "delivery_not_shipping_2": "Choisissez un",
    "delivery_not_shipping_3": "autre emplacement",
    "delivery_not_shipping_4": "ou optez pour",
    "delivery_not_shipping_5": "le retrait",
    "delivery_product_invalid": "Les produits marqués en rouge ne sont pas disponibles pour la livraison. Veuillez les retirer ou optez pour le retrait.",
    "delivery_product_not_sale": "Les produits marqués en rouge ne sont pas disponibles pour ce groupe.",
    "delivery_product_not_sale_pop": "Un ou plusieurs produits ne sont pas disponibles pour ce groupe.",
    "delivery_product_not_shipping": "Un ou plusieurs produits ne sont pas disponibles pour la livraison.",
    "desktop_empty_cart": "Faites un choix dans le menu pour commencer votre commande.",
    "type_takeout_description": "À emporter à ",
    "type_delivery_description": "Votre commande livrée à une adresse de votre choix.",
    "type_group_description": "Commandez avec votre entreprise, groupe ou classe.",
    "add": "Ajouter",
    "facts": "Détails",
    "type_not_active": "Il n'est pas possible d'ajouter des produits à votre panier. Veuillez contacter l'exploitant.",
    "group_inactive": "Ce groupe n'est plus actif. Veuillez contacter l'exploitant.",
    "service_cost": "Servicekost",
    "service_cost_always_charge_on": "{workspaceName} hanteert een servicekost van {cost}",
    "service_cost_always_charge_off": "{workspaceName} hanteert een servicekost van {cost} tot een bestelbedrag van {price}",
} as const
