export default {
    "lang-value": "nl",
    "title": "Bienvenue à",
    "valid": "obligatoire",
    "optional": "Facultatif",
    "loading": "Chargement...",
    "welcome": "Bienvenue à",
    "introduce": "Découvrez notre menu et passez votre commande pour la consommer sur place.",
    "introduce-self": "Découvrez notre menu et passez votre commande à emporter.",
    "view-menu": "Voir notre menu",
    "make-choice": "Faites votre choix",
    "enter-tb-number": "Entrez votre numéro de table",
    "chose-payment": "Choisissez un mode de paiement",
    "start-order": "COMMENCEZ VOTRE COMMANDE",
    "login": "Se connecter",
    "login-nl": "Se connecter",
    "log-in": "Se connecter",
    "login-title": "Connectez-vous ou créez un compte It's Ready pour commander chez votre établissement préféré.",
    "sub-login-title-1": "Connectez-vous ou créez un",
    "sub-login-title-2": "It's Ready",
    "sub-login-title-3": "compte et commandez chez votre établissement préféré",
    "login-with": "Se connecter avec",
    "forget-password": "Mot de passe oublié ?",
    "register": "Pas encore de compte ? \n Inscrivez-vous ici",
    "register-account": "S'inscrire",
    "register-btn": "S'inscrire",
    "missing-fields": "Veuillez remplir tous les champs.",
    "first-name-contain-number": "Complétez votre compte. Le premier champ doit être votre prénom.",
    "profile": "Profil",
    "change-profile": "Modifier le profil",
    "more-information": "Plus d'informations",
    "terms-and-conditions": "Conditions générales",
    "privacy-policy": "Politique de confidentialité",
    "cookie-policy": "Politique en matière de cookies",
    "privacy-policy-portal": "Politique de confidentialité",
    "follow-on-facebook": "Suivez-nous sur Facebook",
    "language": "Langue",
    "login-or-register": "Se connecter ou s'inscrire",
    "logout": "Se déconnecter",
    "nederlands": "Néerlandais",
    "english": "Anglais",
    "frans": "Français",
    "save": "Sauvegarder",
    "no-cancel": "Non, annuler",
    "yes-logout": "Oui, se déconnecter",
    "confirm-logout": "Êtes-vous sûr de vouloir vous déconnecter ?",
    "shipping-fee": "Frais de livraison minimum",
    "min-order": "Commande minimale",
    "min-waiting": "Temps d'attente minimum pour la livraison",
    "delivery": "Livraison",
    "its-ready": "It's Ready",
    "current-location": "Utiliser la localisation actuelle",
    "recently-location": "Localisations récentes",
    "my-location": "Utiliser mon adresse",
    "location": "Utiliser la localisation",
    "not-now": "Pas maintenant",
    "terms": "It's Ready © 2024",
    "label_new": "Nouveau",
    "home": "Accueil",
    "menu": "Menu",
    "shopping-cart": "Panier",
    "not-available": "Non disponible",
    "no-items": "Aucun article",
    "no-items-desk": "Aucun article trouvé dans cette catégorie.",
    "nothing-at-all": "Aucun article trouvé",
    "nothing-at-all-desk": "Aucun produit trouvé",
    "no-favorite-items": "Aucun favori trouvé",
    "read_more": "Lire la suite >",
    "show_less": "Voir moins",
    "full-name": "Nom et prénom",
    "apply": "Postuler",
    "favorites": "Favoris",
    "required": "Ce champ est obligatoire",
    "create-account": "Créez votre compte It's Ready ici pour continuer.",
    "create-account-1": "Créez votre",
    "create-account-2": "It's Ready",
    "create-account-3": "compte ici pour continuer.",
    "agree": "En créant ce compte, j'accepte les",
    "term-condition": "conditions générales",
    "reset-password-success-message": "Vérifiez votre boîte de réception ou votre dossier de spam et suivez le lien pour réinitialiser votre mot de passe.",
    "invalid-email": "Entrez une adresse e-mail valide.",
    "email-sent": "E-mail envoyé",
    "fields-require": "Ce champ est obligatoire.",
    "email-not-exist": "Votre adresse e-mail n'a pas été reconnue. Veuillez vérifier votre adresse e-mail et réessayer.",
    "recover-title": "Récupérer le mot de passe",
    "recover-subtitle": "Entrez votre adresse e-mail pour récupérer votre mot de passe.",
    "change-password": "Changer le mot de passe",
    "enter-change-password": "Entrez votre nouveau mot de passe.",
    "email-field": "Adresse e-mail",
    "reset-password": "Réinitialiser le mot de passe",
    "setup-password-title": "Définir un nouveau mot de passe",
    "new-password": "Nouveau mot de passe",
    "repeat-password": "Répéter le nouveau mot de passe",
    "save-password": "Sauvegarder le mot de passe",
    "new-password-required": "Veuillez entrer un nouveau mot de passe.",
    "password-min-length": "Veuillez utiliser au moins 6 caractères.",
    "repeat-password-required": "Veuillez répéter votre nouveau mot de passe.",
    "password-not-match": "Les mots de passe ne correspondent pas.",
    "password-changed": "Mot de passe modifié",
    "new-password-success": "Votre nouveau mot de passe a été défini avec succès.",
    "choose_at_least_option": "Veuillez choisir au moins {number}",
    "register-almost": "Presque terminé",
    "register-check": "Vérifiez votre boîte de réception ou le dossier spam et suivez le lien pour activer votre compte.",
    "accpet-terms": "Veuillez accepter les termes et conditions et la politique de confidentialité.",
    "first-name": "Prénom",
    "last-name": "Nom",
    "mobile": "Numéro de téléphone mobile",
    "phone": "Numéro de téléphone",
    "email": "Adresse e-mail",
    "password": "Mot de passe",
    "password-confirm": "Confirmer le mot de passe",
    "enter-address": "Entrez votre adresse ici",
    "format-email": "Cette adresse e-mail n'a pas été reconnue.",
    "stolen": "fermé",
    "free": "GRATUIT",
    "order-history": "Historique des commandes",
    "subtotal": "Sous-total",
    "coupon-discount": "Réduction de coupon",
    "redeem-discount": "Réduction carte client",
    "group-discount": "Réduction de groupe",
    "total": "Total",
    "ordered-items": "Articles commandés",
    "details-order": "Détails de la commande",
    "reorder": "Commander à nouveau",
    "payment-status": "Statut du paiement",
    "payment-method": "Méthode de paiement",
    "comments": "Commentaires",
    "order-type": "Type de commande",
    "take-out": "À emporter",
    "coupon-1": "Allez dans votre panier, entrez ce code et obtenez",
    "coupon-2": "réduction sur votre commande !",
    "coupon-3": "Profitez de",
    "coupon-4": "réduction sur une portion de frites au choix.",
    "coupon-5": "Allez dans votre panier, entrez ce code et obtenez jusqu'à",
    "coupon-6": "réduction sur votre commande !",
    "go-shop": "Aller au panier",
    "upload-avatar-success": "Vous avez changé la photo avec succès",
    "sort-by": "Trier par",
    "standard": "Standard",
    "sort-by-price": "Prix (bas à élevé)",
    "sort-by-name": "Nom (A-Z)",
    "register-button": "Suivant",
    "register-portal": "Compléter",
    "of": "OU",
    "register-with": "S'inscrire avec",
    "vb": "ex.: +32488893344",
    "failed": "Échoué !",
    "invalid-link": "Oups.. Le lien n'est plus valide.",
    "invalid-order": "OUPS... UN PROBLÈME EST SURVENU.",
    "invalid-desktop-title": "LIEN INVALIDE",
    "invalid-table-desktop-description": "Ce site ne prend en charge que la version mobile.",
    "invalid-desktop-description": "Le lien que vous avez utilisé n'est plus valide. Veuillez réessayer.",
    "invalid-desktop-button": "RETOUR À L'ASSORTIMENT",
    "try-again-link": "Le lien que vous avez utilisé n'est plus valide. Veuillez réessayer.",
    "try-again-order": "Votre commande n'a pas été correctement finalisée. Vérifiez votre méthode de paiement et réessayez.",
    "back": "Retour",
    "fits": "Cela va bien avec.",
    "no-thanks": "Continuer la commande",
    "notification": "Messages",
    "close": "Fermer",
    "register-success": "Votre compte a été créé avec succès.",
    "account-created": "Compte créé",
    "ready": "Prêt !",
    "on": "à",
    "am": "AM",
    "pm": "PM",
    "confirm-location": "Confirmer l'adresse",
    "take-away": "À emporter",
    "group-order": "Commande de groupe",
    "datetime": "Date et heure",
    "change-ordertype": "Changer le type de commande ?",
    "change-ordertype-desk": "Changer le type de commande",
    "register-group-first": "Pas encore inscrit en tant que",
    "register-group-second": "et intéressé à commander ?",
    "contact-us": "Contactez-nous",
    "company": "Entreprise",
    "address": "Livraison à l'adresse",
    "on-invoice": "Sur facture",
    "group": "Groupe",
    "at": "à",
    "delivery-fee": "Frais de livraison",
    "tobe-paid": "À payer",
    "online-method": "En ligne",
    "class": "Classe",
    "start-order-popup": "commencer la commande",
    "chose-group": "Choisissez votre groupe",
    "intersted-ordering": "Intéressé à commander en groupe ?",
    "contact-promise": "Nous vous contacterons dès que possible.",
    "telephone-gsm": "Téléphone/GSM",
    "company-label": "Entreprise",
    "city-label": "Ville",
    "send-message": "Envoyer le message",
    "message": "Message",
    "missing-fields-red": "Veuillez remplir tous les champs marqués en rouge",
    "format-gsm": "Au moins 11 chiffres, y compris l'indicatif du pays. ex. +32488896655",
    "contact-success": "Message envoyé avec succès. Nous vous contacterons dès que possible.",
    "message-sent": "Message envoyé avec succès. Nous vous contacterons dès que possible.",
    "fill-all": "Veuillez remplir tous les champs.",
    "in-house": "Sur place",
    "monday": "Lundi",
    "tuesday": "Mardi",
    "wednesday": "Mercredi",
    "thursday": "Jeudi",
    "friday": "Vendredi",
    "saturday": "Samedi",
    "sunday": "Dimanche",
    "reserve": "Réserver",
    "menu-cart": "Menu",
    "share": "Partager",
    "loyalty-cart": "Carte de fidélité",
    "house-number": "Ajouter un numéro de maison",
    "choose-date": "Choisir une date",
    "date-time": "Date & heure",
    "choose-address-question": "À quelle adresse souhaitez-vous recevoir la commande ?",
    "my-address": "MON ADRESSE",
    "confirm": "Confirmer",
    "delete-confirmation": "Êtes-vous sûr de vouloir supprimer cet article ?",
    "yes-remove": "Oui, supprimer",
    "passed": "Réussi !",
    "order-successfully": "Votre commande a été traitée avec succès",
    "check-mail-order-successfully": "Vérifiez votre boîte de réception ou dossier de spam pour une confirmation de commande et un e-mail de rappel",
    "back-to-assortment": "Retour à l'assortiment",
    "back-to-login": "Retour à la connexion",
    "ordered-products": "Produits commandés",
    "Total": "Total",
    "delivery-cost": "Frais de livraison",
    "details-of-order": "Détails de la commande",
    "to-be-paid": "À payer",
    "comment": "Commentaire",
    "cash": "Espèces",
    "pay-cash": "Payer en espèces",
    "online": "Payer en ligne",
    "unknown": "À payer",
    "pending": "À payer",
    "paid": "Payé",
    "cancelled": "Annulé",
    "expired": "Expiré",
    "show_more": "Voir plus",
    "comlete-account-infor": "Complétez votre compte",
    "enter-first-name-phone": "Entrez les informations manquantes pour compléter votre compte.",
    "account": "Compte",
    "choose-online-method": "Choisissez un mode de paiement en ligne",
    "choose-online-method-desktop": "Choisissez votre mode de paiement en ligne préféré.",
    "cash-payment": "Sur place",
    "cash-payment-delivery": "Au livreur",
    "cash-payment-desktop": "Sur place.",
    "cash-payment-desktop-delivery": "Au livreur.",
    "receive-invoice": "Vous recevrez une facture",
    "receive-invoice-desktop": "Recevez une facture et payez plus tard.",
    "close-time": "Commander jusqu'à",
    "no-result": "Aucun résultat trouvé",
    "go-to": "Aller à",
    "my-profile": "Mon profil",
    "save-address": "et enregistrez votre adresse",
    "enter-infores": "Entrez ici le nom de votre entreprise, groupe ou classe",
    "email-fail": "Veuillez entrer une adresse e-mail valide.",
    "mobile-plus": "Téléphone/Mobile",
    "receive-up-to": "Recevez jusqu'à",
    "discount-next-order": "remise sur votre prochaine commande",
    "redeem": "Échanger",
    "adres": "Adresse",
    "change-avatar": "Cliquez ci-dessous pour modifier votre photo de profil",
    "click-here": "Cliquez ici",
    "to-change-photo": "pour modifier votre photo de profil.",
    "check-mail-gift": "Une copie de ce message a été envoyée par e-mail. Vérifiez votre boîte de réception.",
    "request-gift": "Demandez votre cadeau au restaurant et montrez ce message !",
    "redeemed": "Déjà échangé",
    "credits-required": "Crédits nécessaires",
    "successful-redeem": "Échange réussi",
    "auto-deducted-shopping-cart": "Votre réduction de carte de fidélité a été automatiquement appliquée à votre panier",
    "applied-to-next-order": "Votre remise sera automatiquement appliquée lors de votre prochaine commande.",
    "must-use-redeemed-discount": "Vous avez déjà échangé cette remise ! Passez une commande et utilisez cette remise !",
    "with-out": "Sans ",
    "home-bottom1": "Découvrez notre assortiment →",
    "home-bottom2": "Commencez votre commande",
    "opps": "Oups..",
    "edit-date": "Modifier la date",
    "edit-time": "Modifier l'heure",
    "group-ordering": "Commande pour",
    "remove-products": "Supprimer les produits",
    "unavailable-products": "Les produits marqués en rouge ne sont pas disponibles.",
    "not-delivery-products": "Les produits marqués en rouge ne sont pas disponibles pour la livraison.",
    "invalidate-date": "Un ou plusieurs articles ne sont pas disponibles à la date choisie. Choisissez un autre jour ou retirez les articles marqués en rouge de votre panier.",
    "invalidate-time": "Un ou plusieurs articles ne sont pas disponibles à l'heure choisie. Choisissez un autre créneau horaire ou retirez les articles marqués en rouge de votre panier.",
    "customer_card": "Carte client",
    "edit-profile-successfully": "Votre profil a été mis à jour avec succès",
    "unavailable-for-delivery": "Un ou plusieurs produits ne sont pas disponibles pour la livraison",
    "other-register": "Ou enregistrez-vous avec",
    "and": "et",
    "active-account": "Votre compte a été activé et est prêt à l'emploi !",
    "start-order-desk": "Choisissez dans le menu pour commencer votre commande.",
    "searching-input": "Rechercher des produits",
    "email-confirmation": "Confirmer l'adresse e-mail",
    "weekName": "Dimanche, Lundi, Mardi, Mercredi, Jeudi, Vendredi, Samedi",
    "order-type-label": "Retrait, Livraison, Commande de groupe",
    "order-text": "Commande",
    "order-text-empty": "Aucune commande récente disponible",
    "sort-by-price-desk-decen": "Prix (Décroissant)",
    "sort-by-price-desk-acen": "Prix (Croissant)",
    "day-name": "Aujourd'hui",
    "day-name-continue": "jour(s) passé(s)",
    "week-name": "semaine dernière",
    "contact": "Contact",
    "contact-description": "Remplissez les informations ci-dessous si vous souhaitez commander en tant qu'entreprise, groupe ou classe. Nous vous contacterons dans les plus brefs délais !",
    "back-contact": "Retour à la commande",
    "submit-contact": "Envoyer",
    "title-success-contact": "Message envoyé",
    "description-success-contact": "Le message a été envoyé avec succès. Nous vous contacterons dès que possible.",
    "continue-desk": "CONTINUER LA COMMANDE",
    "notification-empty": "Aucun message disponible",
    "notification-read-all": "Tout marquer comme lu",
    "days-name-continue": "Jours auparavant",
    "table-ordering-notfound-title": "Un problème est survenu.",
    "table-ordering-notfound-description": "Un problème s'est produit. Veuillez le signaler au commerçant.",
    "table-ordering-notfound-disable-title": "Actuellement fermé",
    "table-ordering-notfound-disable-description": "Désolé, nous sommes actuellement fermés. Nous serons heureux de vous revoir pendant nos heures d'ouverture ou essayez à nouveau.",
    "table-ordering-notfound-button": "Réessayer",
    "another address": "Une autre adresse",
    "contact-gsm": "Numéro de téléphone portable",
    "step2_title_cart": "Numéro de table",
    "step2_text1": "Entrez le numéro de téléphone de votre appareil mobile. Vous recevrez un SMS à ce numéro lorsque votre commande sera prête.",
    "step2_text2": "Vous recevrez votre reçu par e-mail.",
    "step2_button": "Continuer",
    "step2_email": "Adresse e-mail (facultatif)",
    "status_closed": "Fermé",
    "status_about_to_close": "Va bientôt fermer",
    "status_open": "Ouvert",
    "choose-another-location": "ne livre pas à cet endroit. Choisissez un autre endroit ou revenez en arrière et choisissez le retrait.",
    "enter-delivery": "Entrez ici l'adresse de livraison souhaitée.",
    "invalid-coupon-desk": "Ce code n'est pas correct.",
    "lastest": "dernier",
    "complete": "complet.",
    "not": "pas",
    "not-complete": "pas complet.",
    "step3-1-1": "Je suis le",
    "step3-1-2": "Je suis",
    "step3-2": "et je confirme ainsi la commande de cette table comme",
    "step3-3": "le dernier et marque la commande de cette table comme",
    "check-request-gift-email": "Demandez votre cadeau au restaurant. Une copie de ce message a été envoyée par e-mail. Vérifiez votre boîte de réception.",
    "thank-you-for-order": "Merci pour votre commande",
    "ship-asap": "Votre commande a été expédiée et arrivera dès que possible.",
    "ship-asap-and-keep-phone": "Votre commande a été expédiée et arrivera dès que possible. Assurez-vous de garder votre téléphone à portée de main, vous recevrez une notification lorsque votre commande sera prête à être récupérée.",
    "problem-occurred": "Un problème est survenu.",
    "problem-occurred-and-report": "Un problème est survenu. Veuillez le signaler au commerçant.",
    "try-again": "Réessayer",
    "currently-closed": "Actuellement fermé",
    "closed-order-again": "Désolé, nous sommes actuellement fermés. Nous serons heureux de vous revoir pendant nos heures d'ouverture ou essayez à nouveau.",
    "footer-desktop": "2024 © It’s Ready - Conditions générales - Politique de confidentialité",
    "footer-copyright": "2024 © It’s Ready",
    "footer-terms": "Conditions générales",
    "footer-privacy": "Politique de confidentialité",
    "table-ordering-step2-mess-number": "Message d'erreur.",
    "table-ordering-step2-mess-phone": "Minimum 11 chiffres, y compris l'indicatif du pays. ex. +32488896655",
    "table-ordering-step2-mess-email": "Veuillez entrer une adresse e-mail valide.",
    "self-ordering-notfound-title": "Un problème est survenu.",
    "self-ordering-notfound-description": "Un problème s'est produit. Veuillez le signaler au commerçant.",
    "self-ordering-notfound-button": "Réessayer",
    "self-ordering-notfound-closed-title": "Actuellement fermé",
    "self-ordering-notfound-closed-description": "Désolé, nous sommes actuellement fermés. Nous serons heureux de vous revoir pendant nos heures d'ouverture ou essayez à nouveau.",
    "self-ordering-notfound-closed-button": "Réessayer",
    "step_confirmation": "Confirmation",
    "search-portal": "Rechercher",
    "fill-postal-code": "Entrez votre code postal ici.",
    "man": "Homme",
    "woman": "Femme",
    "en": "et",
    "privacy-portal": "Politique de confidentialité",
    "sub-no-result": "Modifiez vos critères de recherche ou essayez à nouveau.",
    "page-not-found": "Page non trouvée",
    "order-ahead": "Commander à l'avance",
    "profile-edit-success": "Profil mis à jour avec succès",
    "limit_time_to_payment": "Désolé, il n'est plus possible de commander pour l'heure souhaitée. Choisissez une nouvelle heure.",
    "order_continuous": "Continuer à commander",
    "change_step_first_name_invalid": "Entrez votre prénom pour compléter votre compte.",
    "change_step_phone_number_invalid": "Entrez votre numéro de téléphone portable pour compléter votre compte.",
    "change_step_email_invalid": "Entrez votre adresse e-mail pour compléter votre compte.",
    "change_step_common_invalid_format": "Entrez les informations manquantes pour compléter votre compte.",
    "lang_welcome_to_its_ready": "Bienvenue sur It's Ready",
    "lang_login_of_account": "Connectez-vous ou créez un compte et commandez chez votre magasin préféré !",
    "lang_of": "OU", 
    "lang_loading": "Chargement",
    "lang_credits": "Crédits",
    "lang_not_found": "Page non trouvée",
    "lang_could_not_found_resource": "La ressource demandée n'a pas été trouvée",
    "lang_something_went_wrong": "Quelque chose s'est mal passé",
    "lang_try_again": "Essayez à nouveau",
    "lang_coupon_code": "Code coupon",
    "lang_email_valid_message": "Adresse e-mail invalide",
    "lang_sluiten": "FERMER",
    "lang_no_data": "Aucune donnée",
    "lang_afaal": "RETRAIT",
    "lang_levering": "LIVRAISON",
    "lang_groepsbestelling": "COMMANDE DE GROUPE",
    "lang_min": "min",
    "lang_btw": "TVA",
    "lang_tel": "TEL",
    "lang_email_address": "Adresse e-mail",
    "lang_phone_valid_message": "Doit contenir un chiffre",
    "lang_email_form_label": "E-MAIL",
    "lang_gsm_form_label": "Mobile",
    "lang_update_profile": "Mettre à jour le profil",
    "lang_portal_lorem": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eut labore et dolore magna aliqua.",
    "lang_burger_stad": "Ville des Burgers",
    "lang_deluxe": "Hamburger deluxe avec sauce cheddar",
    "lang_itsready_app": "Application It's Ready",
    "lang_account": "Compte",
    "lang_profile_edit": "Modifier le profil",
    "lang_welcome_back": "Bienvenue à nouveau",
    "lang_report": "Rapports",
    "lang_order_history": "Historique des commandes",
    "lang_logout": "Se déconnecter",
    "lang_login": "Se connecter",
    "lang_password_must_match": "Les mots de passe doivent correspondre",
    "security_invalid_description": "Scannez à nouveau le code QR et passez votre commande",
} as const
