export default {
    "search": "Rechercher",
    "free": "Gratuit",
    "take-away" : "À emporter",
    "choose-ordering-method": "Choisissez votre méthode de commande",
    "all": "Tout",
    "close": "Fermé",
    "open": "Ouvert",
    "sort-by": "Trier par",
    "name": "Nom",
    "default": "Par défaut",
    "handelaar": "Commerçant",
    "distance": "Distance",
    "min-price": "Montant minimum",
    "delivery-cost": "Coût de livraison",
    "min-wait-time": "Temps d'attente minimum",
    "search-here": "Rechercher par commerçant",
    "back-to-list": "Retour à la vue liste",
    "back-to-its": "Retour à itsready.be",
    "terms-and-conditions": "Conditions générales",
    "my-account": "Mon compte",
    "home": "Accueil",
    "how-it-work": "Comment ça marche",
    "find-merchants": "Trouver des commerçants",
    "contact": "Contact",
    "enter-address": "Entrez votre adresse ici",
    "search-by-merchant" : "Rechercher par commerçant",
    "merchants-with-loyalty" : "Afficher uniquement les commerçants avec une carte de fidélité",
    "min-order-amount" : "Montant minimum de commande",
    "no-preference" : "Aucune préférence",
    "or-less" : "ou moins",
    "delivery-charge" : "Frais de livraison",
    "register-trader" : "S'inscrire en tant que commerçant",
    "new-traders" : "Nouveaux commerçants",
    "trader" : "Commerçant",
    "cookie-policy" : "Politique de cookies",
    "filters" : "Filtres",
    "opening" : "Ouvert maintenant",
    "group-orders" : "Commandes groupées",
    "promoties" : "Promotions",
    "map-view" : "Vue carte",
    "list-view" : "Vue liste",
    "no-result" : "Aucun commerçant trouvé",
    "sub-no-result" : "Modifiez vos critères de recherche ou essayez à nouveau.",
    "navigation" : "Navigation",
    "find-dealer" : "Trouver un commerçant",
    "traders-website" : "Site web du commerçant",
    "craving-something" : "Envie de quelque chose",
    "tasty" : "Délicieux",
    "home-placeholder" : "Code postal, ville ou commune",
    "3-steps" : "Satisfaire votre faim en 3 étapes",
    "choose-trader" : "Choisissez votre commerçant préféré",
    "sub-choose-trader" : "Envie de grec ou à la recherche d'un bon boulanger ? Dîner copieux ou encas rapide ? Tout est possible ! Entrez un emplacement et découvrez les restaurants & commerçants près de chez vous.",
    "choose-payment" : "Choisissez votre méthode de paiement",
    "sub-choose-payment" : "Évitez les longues files d'attente et choisissez l'emporté ou la livraison à l'heure de votre choix. Préférez-vous commander en tant qu'entreprise ou classe ? Demandez facilement et rapidement votre compte groupe. Chaque membre du groupe paie individuellement via l'app ou le web.",
    "download-app" : "Télécharger l'app",
    "sub-download-app" : "Commandez tous les délicieux repas directement via votre téléphone et profitez de nombreux avantages",
    "dishes-at-hand" : "Vos plats préférés toujours à portée de main",
    "loyalty-merchants-together" : "Toutes les cartes de fidélité de vos commerçants préférés réunies",
    "promotions-and-offers" : "Restez informé des promotions et des offres",
    "save-points" : "Passez votre commande & collectez des points",
    "sub-save-points" : "Choisissez dans le menu ou utilisez votre historique de commande et payez facilement en ligne, en espèces ou sans contact. Plus besoin de cartes de fidélité ! Collectez des points facilement pour de belles récompenses, nous suivons tous vos points.",
    "cookie-message" : "Nous utilisons des cookies pour vous offrir la meilleure expérience sur notre site web. Pour plus d'informations, consultez la",
    "cookie-message-link" : "politique de cookies",
    "contact-with-us" : "Contactez-nous",
    "typy-here-first-name" : "Entrez votre prénom ici",
    "typy-here-last-name" : "Entrez votre nom ici",
    "typy-here-email" : "Entrez votre adresse e-mail ici",
    "typy-here-message" : "Entrez votre question ou commentaire ici.",
    "typy-here-phone" : "Entrez votre numéro de téléphone ici",
    "sub-contact-success" : "Nous faisons de notre mieux pour vous répondre dans les plus brefs délais !",
    "sub-contact-with-email" : "Vous avez remarqué une erreur ou avez une question pour nous ? Faites-le nous savoir et nous vous aiderons rapidement. Vous pouvez toujours nous contacter à l'adresse e-mail",
} as const
