export const BASE_URL = process.env.NEXT_PUBLIC_URL
export const API_URL = process.env.NEXT_PUBLIC_API_URL
export const WORKSPACE_TOKEN = process.env.NEXT_PUBLIC_WORKSPACE_TOKEN
export const LANGUAGE_CODE = process.env.NEXT_PUBLIC_LANGUAGE_CODE
export const PUBLIC_GOOGLE_MAPS_API_KEY = process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
export const PUBLIC_GOOGLE_MAPS_API_KEY_AUTOCOMPLETE = process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY_AUTOCOMPLETE
export const PUBLIC_GOOGLE_MAPS_API_KEY_DISTANCE = process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY_DISTANCE
export const VALIDATION_PHONE_MIN = 12;
export const VALIDATION_PHONE_MAX = 19;
export const EXCEPT_DOMAIN = process.env.NEXT_PUBLIC_EXCEPT_DOMAIN
export const TIMEZONE = process.env.NEXT_PUBLIC_TIMEZONE
export const PORTAL_WEBSITE = process.env.NEXT_PUBLIC_PORTAL_WEBSITE_DOMAIN || ''
export const NEXT_DEVICE_LANGUAGE_CODE = process.env.NEXT_DEVICE_LANGUAGE_CODE || ''
export const WEBSITE_DOMAIN = process.env.NEXT_PUBLIC_WEBSITE_DOMAIN || ''
export const TERMS_CONDITIONS_LINK = process.env.NEXT_PUBLIC_TERMS_CONDITIONS_LINK || 'https://b2b.itsready.be/algemene-voorwaarden'
export const PRIVACY_POLICY_LINK = process.env.NEXT_PUBLIC_PRIVACY_POLICY_LINK || 'https://b2b.itsready.be/privacyverklaring'
export const REGEX_NUMBER_CHECK = /\d/;
export const OPENING_HOUR_TABLE_ORDERING_TYPE = 2;
export const EXTRA_SETTING_TABLE_ORDERING_TYPE = 10;
export const OPENING_HOUR_SELF_ORDERING_TYPE = 3;
export const EXTRA_SETTING_SELF_ORDERING_TYPE = 12;
export const ORIGIN_NEXT = 'next';