export default {
    "empty_cart": "Beginnen Sie Ihre Bestellung, indem Sie ein Produkt in Ihren Warenkorb legen.",
    "view_range": "Sortiment anzeigen",
    "subtotal": "Zwischensumme",
    "coupon_discount": "Gutscheinrabatt",
    "group_discount": "Gruppenrabatt",
    "redeem_discount": "Kundenkartenrabatt",
    "coupon_code": "Gutscheincode",
    "apply_redeem_discount": "Drücken Sie hier, um Ihren Kundenkartenrabatt anzuwenden",
    "apply_redeem_discount_desk": "Drücken Sie hier, um Ihren Kundenkartenrabatt zu nutzen.",
    "total": "Gesamt",
    "apply_coupon": "Anwenden",
    "comment": "Bemerkungen",
    "further": "Weiter",
    "step_overview": "Bestellübersicht",
    "step_table_number": "Tischnummer",
    "step_confirmation": "Bestätigung",
    "step_payment_method": "Zahlungsmethode",
    "product_added_success": "Produkt zum Warenkorb hinzugefügt",
    "product_not_available": "Produkte, die rot markiert sind, sind nicht verfügbar",
    "product_option_not_available": "Produkte und/oder Produktoptionen, die rot markiert sind, sind nicht verfügbar",
    "message_invalid_coupon_product": "Rabatt gilt nicht für die Produkte in Ihrem Warenkorb.",
    "message_apply_coupon_successfully": "Gutscheincode erfolgreich angewendet.",
    "message_apply_coupon_failed": "Bitte fügen Sie zuerst ein Produkt zu Ihrem Warenkorb hinzu.",
    "oops": "Ups",
    "product_impossible_contact_admin": "Es ist nicht möglich, Produkte zu Ihrem Warenkorb hinzuzufügen. Bitte wenden Sie sich an den Betreiber.",
    "back": "Zurück",
    "delivery_free_from": "Kostenlose Lieferung ab",
    "delivery_minimum": "{workspaceName} hat einen Mindestbestellwert von: {price} exkl. Lieferkosten",
    "delivery_minimum-desk": "{workspaceName} hat einen Mindestbestellwert von: {price} exkl. Lieferkosten",
    "delivery_costs": "Lieferkosten",
    "delivery_not_shipping_1": "{workspaceName} liefert nicht an diesen Standort.",
    "delivery_not_shipping_2": "Wählen Sie eine",
    "delivery_not_shipping_3": "andere Adresse",
    "delivery_not_shipping_4": "oder wählen Sie",
    "delivery_not_shipping_5": "Abholung",
    "delivery_product_invalid": "Produkte, die rot markiert sind, sind für die Lieferung nicht verfügbar. Bitte entfernen Sie diese oder wählen Sie Abholung.",
    "delivery_product_not_sale": "Produkte, die rot markiert sind, sind für diese Gruppe nicht verfügbar.",
    "delivery_product_not_sale_pop": "Ein oder mehrere Produkte sind für diese Gruppe nicht verfügbar.",
    "delivery_product_not_shipping": "Ein oder mehrere Produkte sind für die Lieferung nicht verfügbar.",
    "desktop_empty_cart": "Wählen Sie ein Menü aus, um Ihre Bestellung zu starten.",
    "type_takeout_description": "Abholung bei ",
    "type_delivery_description": "Ihre Bestellung wird an eine Adresse Ihrer Wahl geliefert.",
    "type_group_description": "Bestellen Sie mit Ihrem Unternehmen, Ihrer Gruppe oder Klasse.",
    "add": "Hinzufügen",
    "facts": "Details",
    "type_not_active": "Es ist nicht möglich, Produkte zu Ihrem Warenkorb hinzuzufügen. Bitte wenden Sie sich an den Betreiber.",
    "group_inactive": "Diese Gruppe ist nicht mehr aktiv. Bitte wenden Sie sich an den Betreiber.",
    "service_cost": "Servicekost",
    "service_cost_always_charge_on": "{workspaceName} hanteert een servicekost van {cost}",
    "service_cost_always_charge_off": "{workspaceName} hanteert een servicekost van {cost} tot een bestelbedrag van {price}",
} as const