export default {
    "lang-value": "nl",
    "title": "Willkommen bei",
    "valid": "erforderlich",
    "optional": "Optional",
    "loading": "Lädt...",
    "welcome": "Willkommen bei",
    "introduce": "Entdecken Sie unsere Speisekarte und geben Sie Ihre Bestellung auf, um vor Ort zu genießen.",
    "introduce-self": "Entdecken Sie unsere Speisekarte und geben Sie Ihre Bestellung auf, um sie mitzunehmen.",
    "view-menu": "Speisekarte ansehen",
    "make-choice": "Wählen Sie Ihre Auswahl",
    "enter-tb-number": "Geben Sie Ihre Tischnummer ein",
    "chose-payment": "Wählen Sie eine Zahlungsmethode",
    "start-order": "STARTEN SIE IHRE BESTELLUNG",
    "login": "Anmelden",
    "login-nl": "Einloggen",
    "log-in": "Einloggen",
    "login-title": "Melden Sie sich an oder erstellen Sie ein It's Ready-Konto, um bei Ihrem Lieblingsgeschäft zu bestellen.",
    "sub-login-title-1": "Melden Sie sich an oder erstellen Sie ein",
    "sub-login-title-2": "It's Ready",
    "sub-login-title-3": "Konto und bestellen Sie bei Ihrem Lieblingsgeschäft",
    "login-with": "Einloggen mit",
    "forget-password": "Passwort vergessen?",
    "register": "Noch kein Konto? \n Registrieren Sie sich hier",
    "register-account": "Registrieren",
    "register-btn": "Registrieren",
    "missing-fields": "Bitte füllen Sie alle Felder aus.",
    "first-name-contain-number": "Vervollständigen Sie Ihr Konto. Das erste Feld muss Ihr Vorname sein.",
    "profile": "Profil",
    "change-profile": "Profil ändern",
    "more-information": "Mehr Informationen",
    "terms-and-conditions": "Allgemeine Geschäftsbedingungen",
    "privacy-policy": "Datenschutzerklärung",
    "cookie-policy": "Cookie-Richtlinie",
    "privacy-policy-portal": "Datenschutzrichtlinie",
    "follow-on-facebook": "Folgen Sie uns auf Facebook",
    "language": "Sprache",
    "login-or-register": "Einloggen oder registrieren",
    "logout": "Abmelden",
    "nederlands": "Niederländisch",
    "english": "Englisch",
    "frans": "Französisch",
    "save": "Speichern",
    "no-cancel": "Nein, abbrechen",
    "yes-logout": "Ja, abmelden",
    "confirm-logout": "Sind Sie sicher, dass Sie sich abmelden möchten?",
    "shipping-fee": "Mindestliefergebühr",
    "min-order": "Mindestbestellwert",
    "min-waiting": "Mindestwartezeit für die Lieferung",
    "delivery": "Lieferung",
    "its-ready": "It's Ready",
    "current-location": "Aktuellen Standort verwenden",
    "recently-location": "Kürzlich verwendete Standorte",
    "my-location": "Mein Adresse verwenden",
    "location": "Standort verwenden",
    "not-now": "Nicht jetzt",
    "terms": "It's Ready © 2024",
    "label_new": "Neu",
    "home": "Startseite",
    "menu": "Menü",
    "shopping-cart": "Warenkorb",
    "not-available": "Nicht verfügbar",
    "no-items": "Keine Artikel",
    "no-items-desk": "Keine Artikel in dieser Kategorie gefunden.",
    "nothing-at-all": "Keine Artikel gefunden",
    "nothing-at-all-desk": "Keine Produkte gefunden",
    "no-favorite-items": "Keine Favoriten gefunden",
    "read_more": "Mehr lesen >",
    "show_less": "Weniger anzeigen",
    "full-name": "Vor- und Nachname",
    "apply": "Bewerben",
    "favorites": "Favoriten",
    "required": "Dieses Feld ist erforderlich",
    "create-account": "Erstellen Sie hier Ihr It's Ready-Konto, um fortzufahren.",
    "create-account-1": "Erstellen Sie hier Ihr",
    "create-account-2": "It's Ready",
    "create-account-3": "Konto, um fortzufahren.",
    "agree": "Durch die Erstellung dieses Kontos stimme ich den",
    "term-condition": "Allgemeinen Geschäftsbedingungen zu",
    "reset-password-success-message": "Überprüfen Sie Ihren Posteingang oder Spam-Ordner und folgen Sie dem Link, um Ihr Passwort zurückzusetzen.",
    "invalid-email": "Geben Sie eine gültige E-Mail-Adresse ein.",
    "email-sent": "E-Mail gesendet",
    "fields-require": "Dieses Feld ist erforderlich.",
    "email-not-exist": "Ihre E-Mail-Adresse wurde nicht erkannt. Überprüfen Sie Ihre E-Mail-Adresse und versuchen Sie es erneut.",
    "recover-title": "Passwort wiederherstellen",
    "recover-subtitle": "Geben Sie Ihre E-Mail-Adresse ein, um Ihr Passwort wiederherzustellen.",
    "change-password": "Passwort ändern",
    "enter-change-password": "Geben Sie Ihr neues Passwort ein.",
    "email-field": "E-Mail-Adresse",
    "reset-password": "Passwort zurücksetzen",
    "setup-password-title": "Neues Passwort festlegen",
    "new-password": "Neues Passwort",
    "repeat-password": "Neues Passwort wiederholen",
    "save-password": "Passwort festlegen",
    "new-password-required": "Bitte geben Sie ein neues Passwort ein.",
    "password-min-length": "Bitte verwenden Sie mindestens 6 Zeichen.",
    "repeat-password-required": "Bitte wiederholen Sie Ihr neues Passwort.",
    "password-not-match": "Passwörter stimmen nicht überein.",
    "password-changed": "Passwort geändert",
    "new-password-success": "Ihr neues Passwort wurde erfolgreich festgelegt.",
    "choose_at_least_option": "Bitte wählen Sie mindestens {number}",
    "register-almost": "Fast fertig",
    "register-check": "Überprüfen Sie Ihr Postfach oder den Spam-Ordner und folgen Sie dem Link, um Ihr Konto zu aktivieren.",
    "accpet-terms": "Bitte stimmen Sie den Allgemeinen Geschäftsbedingungen und der Datenschutzerklärung zu.",
    "first-name": "Vorname",
    "last-name": "Nachname",
    "mobile": "Mobiltelefonnummer",
    "phone": "Telefonnummer",
    "email": "E-Mail-Adresse",
    "password": "Passwort",
    "password-confirm": "Passwort bestätigen",
    "enter-address": "Geben Sie hier Ihre Adresse ein",
    "format-email": "Diese E-Mail-Adresse wurde nicht erkannt.",
    "stolen": "geschlossen",
    "free": "KOSTENLOS",
    "order-history": "Bestellverlauf",
    "subtotal": "Zwischensumme",
    "coupon-discount": "Rabattcoupon",
    "redeem-discount": "Kundenkartengutschein",
    "group-discount": "Gruppenrabatt",
    "total": "Gesamt",
    "ordered-items": "Bestellte Artikel",
    "details-order": "Bestellungsdetails",
    "reorder": "Erneut bestellen",
    "payment-status": "Zahlungsstatus",
    "payment-method": "Zahlungsmethode",
    "comments": "Kommentare",
    "order-type": "Bestelltyp",
    "take-out": "Abholung",
    "coupon-1": "Gehen Sie zu Ihrem Warenkorb, geben Sie diesen Code ein und erhalten Sie",
    "coupon-2": "Rabatt auf Ihre Bestellung!",
    "coupon-3": "Genießen Sie",
    "coupon-4": "Rabatt auf eine beliebige Portion Pommes.",
    "coupon-5": "Gehen Sie zu Ihrem Warenkorb, geben Sie diesen Code ein und erhalten Sie bis zu",
    "coupon-6": "Rabatt auf Ihre Bestellung!",
    "go-shop": "Gehe zum Warenkorb",
    "upload-avatar-success": "Sie haben das Foto erfolgreich geändert",
    "sort-by": "Sortieren nach",
    "standard": "Standard",
    "sort-by-price": "Preis (niedrig bis hoch)",
    "sort-by-name": "Name (A-Z)",
    "register-button": "Weiter",
    "register-portal": "Abschließen",
    "of": "ODER",
    "register-with": "Registrieren mit",
    "vb": "z.B.: +32488893344",
    "failed": "Fehlgeschlagen!",
    "invalid-link": "Ups.. Der Link ist nicht mehr gültig.",
    "invalid-order": "UPS... ES IST EIN PROBLEM AUFGETRETEN.",
    "invalid-desktop-title": "UNGÜLTIGER LINK",
    "invalid-table-desktop-description": "Diese Website unterstützt nur mobile Ansicht.",
    "invalid-desktop-description": "Der verwendete Link ist nicht mehr gültig. Bitte versuchen Sie es erneut.",
    "invalid-desktop-button": "ZURÜCK ZUR AUSWAHL",
    "try-again-link": "Der verwendete Link ist nicht mehr gültig. Bitte versuchen Sie es erneut.",
    "try-again-order": "Ihre Bestellung wurde nicht korrekt abgeschlossen. Überprüfen Sie Ihre Zahlungsmethode und versuchen Sie es erneut.",
    "back": "Zurück",
    "fits": "Das passt gut dazu.",
    "no-thanks": "Weiter mit der Bestellung",
    "notification": "Nachrichten",
    "close": "Schließen",
    "register-success": "Ihr Konto wurde erfolgreich erstellt.",
    "account-created": "Konto erstellt",
    "ready": "Bereit!",
    "on": "um",
    "am": "AM",
    "pm": "PM",
    "confirm-location": "Standort bestätigen",
    "take-away": "Zum Mitnehmen",
    "group-order": "Gruppenbestellung",
    "datetime": "Datum und Uhrzeit",
    "change-ordertype": "Bestelltyp ändern?",
    "change-ordertype-desk": "Bestelltyp ändern",
    "register-group-first": "Noch nicht registriert als",
    "register-group-second": "und Interesse, zu bestellen?",
    "contact-us": "Kontaktieren Sie uns",
    "company": "Firma",
    "address": "Lieferung an Adresse",
    "on-invoice": "Auf Rechnung",
    "group": "Gruppe",
    "at": "um",
    "delivery-fee": "Liefergebühr",
    "tobe-paid": "Zu bezahlen",
    "online-method": "Online",
    "class": "Klasse",
    "start-order-popup": "Bestellung starten",
    "chose-group": "Wählen Sie Ihre Gruppe",
    "intersted-ordering": "Interessiert, als Gruppe zu bestellen?",
    "contact-promise": "Wir werden so schnell wie möglich mit Ihnen in Kontakt treten.",
    "telephone-gsm": "Telefon/GSM",
    "company-label": "Firma",
    "city-label": "Stadt",
    "send-message": "Nachricht senden",
    "message": "Nachricht",
    "missing-fields-red": "Bitte füllen Sie alle rot markierten Felder aus",
    "format-gsm": "Mindestens 11 Ziffern einschließlich Ländervorwahl. z.B. +32488896655",
    "contact-success": "Nachricht wurde erfolgreich gesendet. Wir werden so schnell wie möglich mit Ihnen in Kontakt treten.",
    "message-sent": "Nachricht wurde erfolgreich gesendet. Wir werden so schnell wie möglich mit Ihnen in Kontakt treten.",
    "fill-all": "Bitte füllen Sie alle Felder aus.",
    "in-house": "Vor Ort",
    "monday": "Montag",
    "tuesday": "Dienstag",
    "wednesday": "Mittwoch",
    "thursday": "Donnerstag",
    "friday": "Freitag",
    "saturday": "Samstag",
    "sunday": "Sonntag",
    "reserve": "Reservieren",
    "menu-cart": "Speisekarte",
    "share": "Teilen",
    "loyalty-cart": "Kundenkarte",
    "house-number": "Hausnummer hinzufügen",
    "choose-date": "Wählen Sie ein Datum",
    "date-time": "Datum & Uhrzeit",
    "choose-address-question": "An welche Adresse möchten Sie die Bestellung liefern lassen?",
    "my-address": "MEINE ADRESSE",
    "confirm": "Bestätigen",
    "delete-confirmation": "Sind Sie sicher, dass Sie dieses Element löschen möchten?",
    "yes-remove": "Ja, löschen",
    "passed": "Bestanden!",
    "order-successfully": "Ihre Bestellung wurde erfolgreich verarbeitet",
    "check-mail-order-successfully": "Überprüfen Sie Ihr Postfach oder Spam-Ordner auf eine Bestellbestätigung und Erinnerungs-E-Mail",
    "back-to-assortment": "Zurück zum Sortiment",
    "back-to-login": "Zurück zur Anmeldung",
    "ordered-products": "Bestellte Artikel",
    "Total": "Gesamt",
    "delivery-cost": "Lieferkosten",
    "details-of-order": "Bestelldetails",
    "to-be-paid": "Zu bezahlen",
    "comment": "Kommentar",
    "cash": "Bargeld",
    "pay-cash": "Bargeld bezahlen",
    "online": "Online bezahlen",
    "unknown": "Zu bezahlen",
    "pending": "Zu bezahlen",
    "paid": "Bezahlt",
    "cancelled": "Storniert",
    "expired": "Abgelaufen",
    "show_more": "Mehr anzeigen",
    "comlete-account-infor": "Vervollständigen Sie Ihr Konto",
    "enter-first-name-phone": "Geben Sie die fehlenden Daten ein, um Ihr Konto zu vervollständigen.",
    "account": "Konto",
    "choose-online-method": "Wählen Sie eine Online-Zahlungsmethode",
    "choose-online-method-desktop": "Wählen Sie eine Online-Zahlungsmethode aus.",
    "cash-payment": "Vor Ort",
    "cash-payment-delivery": "Beim Lieferanten",
    "cash-payment-desktop": "Vor Ort.",
    "cash-payment-desktop-delivery": "Beim Lieferanten.",
    "receive-invoice": "Sie erhalten eine Rechnung",
    "receive-invoice-desktop": "Erhalten Sie eine Rechnung und zahlen Sie später.",
    "close-time": "Bestellen bis",
    "no-result": "Keine Ergebnisse gefunden",
    "go-to": "Gehe zu",
    "my-profile": "Mein Profil",
    "save-address": "und speichern Sie Ihre Adresse",
    "enter-infores": "Geben Sie hier den Namen Ihres Unternehmens, Ihrer Gruppe oder Klasse ein",
    "email-fail": "Bitte geben Sie eine gültige E-Mail-Adresse ein.",
    "mobile-plus": "Telefon/Mobil",
    "receive-up-to": "Erhalten Sie bis zu",
    "discount-next-order": "Rabatt bei Ihrer nächsten Bestellung",
    "redeem": "Einlösen",
    "adres": "Adresse",
    "change-avatar": "Klicken Sie unten, um Ihr Profilbild zu ändern",
    "click-here": "Klicken Sie hier",
    "to-change-photo": "um Ihr Profilbild zu ändern.",
    "check-mail-gift": "Eine Kopie dieser Nachricht wurde per E-Mail gesendet. Überprüfen Sie Ihr Postfach.",
    "request-gift": "Fordern Sie Ihr Geschenk im Restaurant an und zeigen Sie diese Nachricht!",
    "redeemed": "Bereits eingelöst",
    "credits-required": "Credits erforderlich",
    "successful-redeem": "Erfolgreich eingelöst",
    "auto-deducted-shopping-cart": "Ihr Kundenkartenrabatt wurde automatisch im Warenkorb verrechnet",
    "applied-to-next-order": "Ihr Rabatt wird automatisch bei Ihrer nächsten Bestellung verrechnet.",
    "must-use-redeemed-discount": "Sie haben diesen Rabatt bereits eingelöst! Tätigen Sie eine Bestellung und nutzen Sie diesen Rabatt!",
    "with-out": "Ohne ",
    "home-bottom1": "Entdecken Sie unser Sortiment →",
    "home-bottom2": "Starten Sie Ihre Bestellung",
    "opps": "Ups..",
    "edit-date": "Datum ändern",
    "edit-time": "Zeit ändern",
    "group-ordering": "Bestellung für",
    "remove-products": "Produkte entfernen",
    "unavailable-products": "Produkte, die rot markiert sind, sind nicht verfügbar.",
    "not-delivery-products": "Produkte, die rot markiert sind, sind nicht zur Lieferung verfügbar.",
    "invalidate-date": "Ein oder mehrere Artikel sind am von Ihnen gewählten Tag nicht verfügbar. Wählen Sie einen anderen Tag oder entfernen Sie die rot markierten Artikel aus Ihrem Warenkorb.",
    "invalidate-time": "Ein oder mehrere Artikel sind zur von Ihnen gewählten Zeit nicht verfügbar. Wählen Sie einen anderen Zeitraum oder entfernen Sie die rot markierten Artikel aus Ihrem Warenkorb.",
    "customer_card": "Kundenkarte",
    "edit-profile-successfully": "Ihr Profil wurde erfolgreich geändert",
    "unavailable-for-delivery": "Ein oder mehrere Produkte sind nicht für die Lieferung verfügbar",
    "other-register": "Oder registrieren mit",
    "and": "und",
    "active-account": "Ihr Konto wurde aktiviert und ist einsatzbereit!",
    "start-order-desk": "Wählen Sie aus der Speisekarte, um Ihre Bestellung zu starten.",
    "searching-input": "Nach Produkten suchen",
    "email-confirmation": "E-Mail-Adresse bestätigen",
    "weekName": "Sonntag, Montag, Dienstag, Mittwoch, Donnerstag, Freitag, Samstag",
    "order-type-label": "Abholung, Lieferung, Gruppenbestellung",
    "order-text": "Bestellung",
    "order-text-empty": "Keine aktuellen Bestellungen verfügbar",
    "sort-by-price-desk-decen": "Preis (Absteigend)",
    "sort-by-price-desk-acen": "Preis (Aufsteigend)",
    "day-name": "Heute",
    "day-name-continue": "vor einem Tag",
    "week-name": "vor einer Woche",
    "contact": "Kontakt",
    "contact-description": "Füllen Sie die untenstehenden Daten aus, wenn Sie als Unternehmen, Gruppe oder Klasse bestellen möchten. Wir werden uns schnellstmöglich mit Ihnen in Verbindung setzen!",
    "back-contact": "Zurück zur Bestellung",
    "submit-contact": "Absenden",
    "title-success-contact": "Nachricht gesendet",
    "description-success-contact": "Die Nachricht wurde erfolgreich gesendet. Wir werden uns so schnell wie möglich mit Ihnen in Verbindung setzen.",
    "continue-desk": "WEITER MIT BESTELLEN",
    "notification-empty": "Keine Nachrichten verfügbar",
    "notification-read-all": "Alle als gelesen markieren",
    "days-name-continue": "Tage her",
    "table-ordering-notfound-title": "Es ist ein Problem aufgetreten.",
    "table-ordering-notfound-description": "Es gibt ein Problem. Bitte melden Sie es dem Händler.",
    "table-ordering-notfound-disable-title": "Derzeit geschlossen",
    "table-ordering-notfound-disable-description": "Leider sind wir derzeit geschlossen. Wir freuen uns, Sie während unserer Öffnungszeiten wieder zu sehen oder versuchen Sie es erneut.",
    "table-ordering-notfound-button": "Erneut versuchen",
    "another address": "Eine andere Adresse",
    "contact-gsm": "Handynummer",
    "step2_title_cart": "Tischnummer",
    "step2_text1": "Geben Sie die Handynummer Ihres Geräts an. Sie erhalten eine SMS an diese Nummer, wenn Ihre Bestellung fertig ist.",
    "step2_text2": "Sie erhalten Ihren Kassenbon per E-Mail.",
    "step2_button": "Weiter",
    "step2_email": "E-Mail-Adresse (optional)",
    "status_closed": "Geschlossen",
    "status_about_to_close": "Wird bald geschlossen",
    "status_open": "Geöffnet",
    "choose-another-location": "liefert nicht an diesem Standort. Wählen Sie einen anderen Standort oder gehen Sie zurück und wählen Sie Abholung.",
    "enter-delivery": "Geben Sie hier Ihre gewünschte Lieferadresse ein.",
    "invalid-coupon-desk": "Dieser Code ist nicht korrekt.",
    "lastest": "letzte",
    "complete": "komplett.",
    "not": "nicht",
    "not-complete": "nicht vollständig.",
    "step3-1-1": "Ich bin der",
    "step3-1-2": "Ich bin",
    "step3-2": "und bestätige damit die Bestellung dieses Tisches als",
    "step3-3": "der letzte und markiere die Bestellung dieses Tisches als",
    "check-request-gift-email": "Fordern Sie Ihr Geschenk im Restaurant an. Eine Kopie dieser Nachricht wurde per E-Mail gesendet. Überprüfen Sie Ihr Postfach.",
    "thank-you-for-order": "Vielen Dank für Ihre Bestellung",
    "ship-asap": "Ihre Bestellung wurde versendet und wird so schnell wie möglich eintreffen.",
    "ship-asap-and-keep-phone": "Ihre Bestellung wurde versendet und wird so schnell wie möglich eintreffen. Halten Sie Ihr Telefon bereit, Sie erhalten eine Benachrichtigung, wenn Ihre Bestellung abgeholt werden kann.",
    "problem-occurred": "Es ist ein Problem aufgetreten.",
    "problem-occurred-and-report": "Es gibt ein Problem. Bitte melden Sie es dem Händler.",
    "try-again": "Erneut versuchen",
    "currently-closed": "Derzeit geschlossen",
    "closed-order-again": "Leider sind wir derzeit geschlossen. Wir freuen uns, Sie während unserer Öffnungszeiten wieder zu sehen oder versuchen Sie es erneut.",
    "footer-desktop": "2024 © It’s Ready - Allgemeine Geschäftsbedingungen - Datenschutzerklärung",
    "footer-copyright": "2024 © It’s Ready",
    "footer-terms": "Allgemeine Geschäftsbedingungen",
    "footer-privacy": "Datenschutzerklärung",
    "table-ordering-step2-mess-number": "Fehlermeldung.",
    "table-ordering-step2-mess-phone": "Mindestens 11 Ziffern einschließlich Ländervorwahl. z.B. +32488896655",
    "table-ordering-step2-mess-email": "Bitte geben Sie eine gültige E-Mail-Adresse ein.",
    "self-ordering-notfound-title": "Es ist ein Problem aufgetreten.",
    "self-ordering-notfound-description": "Es gibt ein Problem. Bitte melden Sie es dem Händler.",
    "self-ordering-notfound-button": "Erneut versuchen",
    "self-ordering-notfound-closed-title": "Derzeit geschlossen",
    "self-ordering-notfound-closed-description": "Leider sind wir derzeit geschlossen. Wir freuen uns, Sie während unserer Öffnungszeiten wieder zu sehen oder versuchen Sie es erneut.",
    "self-ordering-notfound-closed-button": "Erneut versuchen",
    "step_confirmation": "Bestätigung",
    "search-portal": "Suchen",
    "fill-postal-code": "Geben Sie hier Ihre Postleitzahl ein.",
    "man": "Mann",
    "woman": "Frau",
    "en": "und",
    "privacy-portal": "Datenschutzrichtlinie",
    "sub-no-result": "Ändern Sie Ihre Suchkriterien oder versuchen Sie es erneut.",
    "page-not-found": "Seite nicht gefunden",
    "order-ahead": "Vorbestellen",
    "profile-edit-success": "Profil erfolgreich aktualisiert",
    "limit_time_to_payment": "Leider ist eine Bestellung für den gewünschten Zeitpunkt nicht mehr möglich. Wählen Sie eine neue Uhrzeit.",
    "order_continuous": "Weiter mit Bestellen",
    "change_step_first_name_invalid": "Geben Sie Ihren Vornamen ein, um Ihr Konto zu vervollständigen.",
    "change_step_phone_number_invalid": "Geben Sie Ihre Handynummer ein, um Ihr Konto zu vervollständigen.",
    "change_step_email_invalid": "Geben Sie Ihre E-Mail-Adresse ein, um Ihr Konto zu vervollständigen.",
    "change_step_common_invalid_format": "Füllen Sie die fehlenden Daten aus, um Ihr Konto zu vervollständigen.",
    "lang_welcome_to_its_ready": "Willkommen bei It's Ready",
    "lang_login_of_account": "Melden Sie sich an oder erstellen Sie ein Konto und bestellen Sie bei Ihrem Lieblingsgeschäft!",
    "lang_of": "ODER", 
    "lang_loading": "Lädt",
    "lang_credits": "Guthaben",
    "lang_not_found": "Seite nicht gefunden",
    "lang_could_not_found_resource": "Die angeforderte Ressource konnte nicht gefunden werden",
    "lang_something_went_wrong": "Etwas ist schief gelaufen",
    "lang_try_again": "Versuchen Sie es erneut",
    "lang_coupon_code": "Gutscheincode",
    "lang_email_valid_message": "Ungültige E-Mail-Adresse",
    "lang_sluiten": "SCHLIESSEN",
    "lang_no_data": "Keine Daten",
    "lang_afaal": "ABHOLEN",
    "lang_levering": "LIEFERUNG",
    "lang_groepsbestelling": "GRUPPENBESTELLUNG",
    "lang_min": "Min",
    "lang_btw": "MwSt",
    "lang_tel": "TEL",
    "lang_email_address": "E-Mail-Adresse",
    "lang_phone_valid_message": "Sollte eine Ziffer enthalten",
    "lang_email_form_label": "E-MAIL",
    "lang_gsm_form_label": "Handy",
    "lang_update_profile": "Profil aktualisieren",
    "lang_portal_lorem": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eut labore et dolore magna aliqua.",
    "lang_burger_stad": "Burger Stadt",
    "lang_deluxe": "Deluxe Hamburger mit Cheddarkäse",
    "lang_itsready_app": "It's Ready App",
    "lang_account": "Konto",
    "lang_profile_edit": "Profil bearbeiten",
    "lang_welcome_back": "Willkommen zurück",
    "lang_report": "Berichte",
    "lang_order_history": "Bestellverlauf",
    "lang_logout": "Abmelden",
    "lang_login": "Anmelden",
    "lang_password_must_match": "Passwörter müssen übereinstimmen",
    "security_invalid_description": "Scannen Sie den QR-Code erneut und geben Sie Ihre Bestellung auf",
} as const
