export default {
    "search": "Suchen",
    "free": "Kostenlos",
    "take-away" : "Abholung",
    "choose-ordering-method": "Wählen Sie Ihre Bestellmethode",
    "all": "Alle",
    "close": "Geschlossen",
    "open": "Geöffnet",
    "sort-by": "Sortieren nach",
    "name": "Name",
    "default": "Standard",
    "handelaar": "Händler",
    "distance": "Entfernung",
    "min-price": "Mindestbetrag",
    "delivery-cost": "Lieferkosten",
    "min-wait-time": "Mindestwartezeit",
    "search-here": "Händler suchen",
    "back-to-list": "Zurück zur Listenansicht",
    "back-to-its": "Zurück zu itsready.be",
    "terms-and-conditions": "Allgemeine Geschäftsbedingungen",
    "my-account": "Mein Konto",
    "home": "Startseite",
    "how-it-work": "Wie es funktioniert",
    "find-merchants": "Händler suchen",
    "contact": "Kontakt",
    "enter-address": "Geben Sie hier Ihre Adresse ein",
    "search-by-merchant" : "Suche nach Händler",
    "merchants-with-loyalty" : "Nur Händler mit Kundenkarte anzeigen",
    "min-order-amount" : "Mindestbestellwert",
    "no-preference" : "Keine Präferenz",
    "or-less" : "oder weniger",
    "delivery-charge" : "Liefergebühr",
    "register-trader" : "Händler registrieren",
    "new-traders" : "Neue Händler",
    "trader" : "Händler",
    "cookie-policy" : "Cookie-Richtlinie",
    "filters" : "Filter",
    "opening" : "Jetzt geöffnet",
    "group-orders" : "Gruppenbestellungen",
    "promoties" : "Aktionen",
    "map-view" : "Kartenansicht",
    "list-view" : "Listenansicht",
    "no-result" : "Keine Händler gefunden",
    "sub-no-result" : "Ändern Sie Ihre Suchkriterien oder versuchen Sie es erneut.",
    "navigation" : "Navigation",
    "find-dealer" : "Händler suchen",
    "traders-website" : "Händlerwebsite",
    "craving-something" : "Lust auf etwas",
    "tasty" : "Leckeres",
    "home-placeholder" : "Postleitzahl, Stadt oder Gemeinde",
    "3-steps" : "Stillen Sie Ihren Hunger in 3 Schritten",
    "choose-trader" : "Wählen Sie Ihren Lieblingshändler",
    "sub-choose-trader" : "Lust auf griechisch oder auf der Suche nach einem Bäcker? Ein umfangreiches Abendessen oder ein schneller Snack? Alles ist möglich! Geben Sie einen Standort ein und entdecken Sie Restaurants & Händler in Ihrer Nähe.",
    "choose-payment" : "Wählen Sie Ihre Zahlungsmethode",
    "sub-choose-payment" : "Vermeiden Sie lange Warteschlangen und wählen Sie Abholung oder Lieferung zu einem beliebigen Zeitpunkt. Möchten Sie als Unternehmen oder Klasse bestellen? Beantragen Sie einfach und schnell Ihr Gruppen-Konto. Jedes Gruppenmitglied zahlt einzeln über die App oder das Web.",
    "download-app" : "App herunterladen",
    "sub-download-app" : "Bestellen Sie alles direkt über Ihr Telefon und genießen Sie zahlreiche Vorteile",
    "dishes-at-hand" : "Ihre Lieblingsgerichte immer griffbereit",
    "loyalty-merchants-together" : "Alle Kundenkarten Ihrer Lieblingshändler zusammen",
    "promotions-and-offers" : "Bleiben Sie auf dem Laufenden über Angebote und Aktionen",
    "save-points" : "Bestellen Sie und sammeln Sie Punkte",
    "sub-save-points" : "Wählen Sie aus dem Menü oder nutzen Sie Ihre Bestellhistorie und zahlen Sie einfach online, bar oder kontaktlos. Keine Kundenkarten mehr nötig! Sammeln Sie mühelos Punkte für tolle Belohnungen, wir behalten alle Punkte für Sie im Blick.",
    "cookie-message" : "Wir verwenden Cookies, um Ihnen die beste Erfahrung auf unserer Website zu bieten. Weitere Informationen finden Sie in der",
    "cookie-message-link" : "Cookie-Richtlinie",
    "contact-with-us" : "Kontaktieren Sie uns",
    "typy-here-first-name" : "Geben Sie hier Ihren Vornamen ein",
    "typy-here-last-name" : "Geben Sie hier Ihren Nachnamen ein",
    "typy-here-email" : "Geben Sie hier Ihre E-Mail-Adresse ein",
    "typy-here-message" : "Geben Sie hier Ihre Frage oder Anmerkung ein.",
    "typy-here-phone" : "Geben Sie hier Ihre Telefonnummer ein",
    "sub-contact-success" : "Wir tun unser Bestes, um Ihnen so schnell wie möglich zu antworten!",
    "sub-contact-with-email" : "Haben Sie einen Fehler bemerkt oder eine Frage an uns? Lassen Sie es uns wissen, und wir helfen Ihnen schnell weiter. Sie können uns auch immer per E-Mail kontaktieren",
} as const
