export default {
    "empty_cart": "Start uw bestelling door een product toe te voegen aan uw winkelmand.",
    "view_range": "Bekijk assortiment",
    "subtotal": "Subtotaal",
    "coupon_discount": "Coupon korting",
    "group_discount": "Groepskorting",
    "redeem_discount": "Klantenkaart korting",
    "coupon_code": "Coupon code",
    "apply_redeem_discount": "Druk hier om uw klantenkaarkorting toe te passen",
    "apply_redeem_discount_desk": "Druk hier om gebruik te maken van uw klantenkaartkorting.",
    "total": "Totaal",
    "apply_coupon": "Toepassen",
    "comment": "Eventuele opmerkingen",
    "further": "Verder",
    "step_overview": "Besteloverzicht",
    "step_table_number": "Tafelnummer",
    "step_confirmation": "Bevestiging",
    "step_payment_method": "Betaalmethode",
    "product_added_success": "Product toegevoegd aan winkelwagen",
    "product_not_available": "Producten aangeduid in het rood zijn niet beschikbaar",
    "product_option_not_available": "Producten en/of productopties aangeduid in het rood zijn niet beschikbaar",
    "message_invalid_coupon_product": "Korting is niet van toepassing op de producten in je winkelmand.",
    "message_apply_coupon_successfully": "Coupon code succesvol toegepast.",
    "message_apply_coupon_failed": "Gelieve eerst een product toe te voegen aan uw winkelmand.",
    "oops": "Oeps",
    "product_impossible_contact_admin": "Het is niet mogelijk om producten toe te voegen aan uw winkelmand. Gelieve contact op te nemen met de uitbater.",
    'back': 'Terug',
    "delivery_free_from": "Gratis levering vanaf",
    "delivery_minimum": "{workspaceName} hanteert een minimum bestelbedrag van: {price} excl. bezorgkosten",
    "delivery_minimum-desk": "{workspaceName} hanteert een minimum bestelbedrag van: {price} excl. bezorgkosten",
    "delivery_costs": "Leverkosten",
    "delivery_not_shipping_1": "{workspaceName} levert niet op deze locatie.",
    "delivery_not_shipping_2": "Kies aan",
    "delivery_not_shipping_3": "andere locatie",
    "delivery_not_shipping_4": "of kies voor",
    "delivery_not_shipping_5": "afhaal",
    "delivery_product_invalid": "Producten aangeduid in het rood zijn niet beschikbaar voor levering. Gelieve deze te verwijderen of te kiezen voor afhaal.",
    "delivery_product_not_sale": "Producten aangeduid in het rood zijn niet beschikbaar voor deze groep.",
    "delivery_product_not_sale_pop": "Één of meer producten zijn niet beschikbaar voor deze groep.",
    "delivery_product_not_shipping": "Één of meer producten zijn niet beschikbaar voor levering.",
    "desktop_empty_cart": "Maak een keuze uit het menu om uw bestelling te starten.",
    "type_takeout_description": "Afhalen op ",
    "type_delivery_description": "Uw bestelling geleverd op een adres naar keuze.",
    "type_group_description": "Bestel met uw bedrijf, groep of klas.",
    "add": "Voeg Toe",
    "facts": "Gegevens",
    "type_not_active": "Het is niet mogelijk om producten toe te voegen aan uw winkelmand. Gelieve contact op te nemen met de uitbater.",
    "group_inactive": "Deze groep is niet langer actief. Gelieve contact op te nemen met de uitbater.",
    "service_cost": "Servicekost",
    "service_cost_always_charge_on": "{workspaceName} hanteert een servicekost van {cost}",
    "service_cost_always_charge_off": "{workspaceName} hanteert een servicekost van {cost} tot een bestelbedrag van {price}",
} as const