export default {
    "lang-value": "nl",
    "title": "Welkom bij",
    "valid": "verplicht",
    "optional": "Optioneel",
    "loading": "Loading...",
    "welcome": "Welkom bij",
    "introduce": "Ontdek onze menukaart en plaats je bestelling om ter plaatse te consumeren.",
    "introduce-self": " Ontdek onze menukaart en plaats je bestelling om mee te nemen.",
    "view-menu": "Bekijk onze menukaart",
    "make-choice": "Maak je keuze",
    "enter-tb-number": "Voer uw tafelnummer in",
    "chose-payment": "Kies een betaalmethode",
    "start-order": "START UW BESTELLING",
    "login": "Login",
    "login-nl": "Inloggen",
    "log-in": "Log in",
    "login-title": "Log in of maak een It's Ready account aan en bestel bij uw favoriete zaak.",
    "sub-login-title-1": "Log in of maak een ",
    "sub-login-title-2": "It's Ready ",
    "sub-login-title-3": "account aan en bestel bij uw favoriete zaak",
    "login-with": "Log in met",
    "forget-password": "Wachtwoord vergeten?",
    "register": "Nog geen account? \n Registreer hier",
    "register-account": "Registreren",
    "register-btn": "Registreer",
    "missing-fields": "Gelieve alle velden in te vullen.",
    "first-name-contain-number": "Vervolledig uw account. Het eerste veld dient uw voornaam te zijn.",
    "profile": "Profiel",
    "change-profile": "Profiel wijzigen",
    "more-information": "Meer informatie",
    "terms-and-conditions": "Algemene voorwaarden",
    "privacy-policy": "Privacyverklaring",
    "cookie-policy": "Cookiebeleid",
    "privacy-policy-portal": "Privacybeleid",
    "follow-on-facebook": "Volgen op Facebook",
    "language": "Taal",
    "login-or-register": "Inloggen of registeren",
    "logout": "Uitloggen",
    "nederlands": "Nederlands",
    "english": "English",
    "frans": "Frans",
    "save": "Opslaan",
    "no-cancel": "Nee, annuleer",
    "yes-logout": "Ja, log uit",
    "confirm-logout": "Bent u zeker dat u wilt uitloggen?",
    "shipping-fee": "Minimale leverkost",
    "min-order": "Levering minimum",
    "min-waiting": "Minimale wachttijd voor levering",
    "delivery": "Levering",
    "its-ready": "It's Ready",
    "current-location": "Gebruik huidige locatie",
    "recently-location": "Recente locaties",
    "my-location": "Gebruik mijn adres",
    "location": "Gebruik locatie",
    "not-now": "Niet nu",
    "terms": "It's ready © 2024 ",
    "label_new": "New",
    "home": "Home",
    "menu": "Menu",
    "shopping-cart": "Winkelmand",
    "not-available": "Niet beschikbaar",
    "no-items": "Geen items",
    "no-items-desk": "Geen items gevonden in deze categorie.",
    "nothing-at-all": "Geen items gevonden",
    "nothing-at-all-desk": "Geen producten gevonden",
    "no-favorite-items": "Geen favorieten gevonden",
    "read_more": " Meer lezen >",
    "show_less": " Minder bekijken",
    "full-name": "Naam en voornaam",
    "apply": "Solliciteren",
    "favorites": "Favorieten",
    "required": "Dit veld is verplicht",
    "create-account": "Maak hier uw It’s Ready account aan om verder te gaan.",
    "create-account-1": "Maak hier uw ",
    "create-account-2": "It’s Ready ",
    "create-account-3": "account aan om verder te gaan.",
    "agree": "Bij het aanmaken van dit account ga ik akkoord met de",
    "term-condition": "algemene voorwaarden",
    "reset-password-success-message": "Controleer uw inbox of spam mailbox en volg de link om uw wachtwoord te herstellen.",
    "invalid-email": "Voer een geldig e-mailadres in.",
    "email-sent": "E-mail verstuurd",
    "fields-require": "Dit veld is verplicht.",
    "email-not-exist":"Uw e-mailadres werd niet herkend. Controleer uw e-mailadres en probeer opnieuw.",
    "recover-title": "Wachtwoord herstellen",
    "recover-subtitle": "Vul uw e-mailadres in om uw wachtwoord te herstellen.",
    "change-password": "Wachtwoord wijzigen",
    "enter-change-password": "Vul uw nieuw wachtwoord.",
    "email-field": "E-mailadres",
    "reset-password":"Wachtwoord herstellen" ,
    "setup-password-title": "Nieuw wachtwoord instellen",
    "new-password": "Nieuw wachtwoord",
    "repeat-password": "Nieuw wachtwoord herhalen",
    "save-password": "Wachtwoord instellen",
    "new-password-required": "Voer alstublieft een nieuw wachtwoord in.",
    "password-min-length": " Gelieve minimum 6 tekens te gebruiken. ",
    "repeat-password-required": "Herhaal alstublieft uw nieuwe wachtwoord.",
    "password-not-match":"Wachtwoorden komen niet overeen.",
    "password-changed":"Wachtwoord gewijzigd",
    "new-password-success":"Uw nieuw wachtwoord is succesvol ingesteld.",
    "choose_at_least_option": "Gelieve minimaal {number} te kiezen",
    "register-almost": "Bijna klaar",
    "register-check": " Controleer uw inbox of spam mailbox en volg de link om uw account te activeren. ",
    "accpet-terms": "Gelieve akkoord te gaan met de algemene voorwaarden en privacyverklaring.",
    "first-name": "Voornaam",
    "last-name": "Naam",
    "mobile": "Mobiel telefoonnummer",
    "phone": "Telefoonnummer",
    "email": "E-mailadres",
    "password": "Wachtwoord",
    "password-confirm": "Wachtwoord herhalen",
    "enter-address" : "Vul hier uw adres in",
    "format-email" : "Dit e-mailadres werd niet herkend.",
    "stolen": "gesloten",
    "free" : "GRATIS",
    "order-history": "Bestelgeschiedenis",
    "subtotal": "Subtotaal",
    "coupon-discount": "Coupon korting",
    "redeem-discount": "Klantenkaart korting",
    "group-discount": "Groepskorting",
    "total": "Totaal",
    "ordered-items": "Bestelde artikelen",
    "details-order":"Details van bestelling",
    "reorder": "Opnieuw bestellen",
    "payment-status": "Betaalstatus",
    "payment-method": "Betaalmethode",
    "comments": "Opmerkingen",
    "order-type": "Type bestelling",
    "take-out": "Afhaal",
    "coupon-1" : "Ga naar uw winkelmand, wissel deze code in en ontvang",
    "coupon-2" : "korting op uw bestelling!",
    "coupon-3" : "Geniet van",
    "coupon-4" : "korting op een friet naar keuze.",
    "coupon-5" : "Ga naar uw winkelmand, wissel deze code in en ontvang maximaal",
    "coupon-6" : "korting op uw bestelling!",
    "go-shop" : "Ga naar winkelmand",
    "upload-avatar-success" : "Je hebt de foto met succes gewijzigd",
    "sort-by" : "Sorteer op",
    "standard" : "Standaard",
    "sort-by-price" : "Prijs (laag naar hoog)",
    "sort-by-name" : "Naam (A-Z)",
    "register-button" : "Volgende",
    "register-portal" : "Voltooien",
    "of": "OF",
    "register-with": "Registeren met",
    "vb": "vb.: +32488893344",
    "failed" : "Mislukt!",
    "invalid-link": "Oeps.. De link is niet meer geldig.",
    "invalid-order": "OEPS... ER IS EEN PROBLEEM OPGETREDEN.",
    "invalid-desktop-title": "ONGELDIGE LINK",
    "invalid-table-desktop-description": "Deze website ondersteunt alleen mobiele responsiviteit.",
    "invalid-desktop-description": "De link die u gebruikt heeft is niet meer geldig. Gelieve opnieuw te proberen.",
    "invalid-desktop-button": "TERUG NAAR HET ASSORTIMENT",
    "try-again-link" : "De link die u gebruikt heeft is niet meer geldig. Gelieve opnieuw te proberen.",
    "try-again-order" : "Uw bestelling werd niet correct afgerond. Controleer uw betaalmethode en probeer het opnieuw.",
    "back" : "Terug",
    "fits" : "Dit past er lekker bij.",
    "no-thanks" : "Verder met bestellen",
    "notification": "Berichten",
    "close": "Sluiten",
    "register-success" : "Uw account is succesvol aangemaakt.",
    "account-created" : "Account aangemaakt",
    "ready": "Ready!",
    "on": "om",
    "am": "AM",
    "pm": "PM",
    "confirm-location": "Bevestig locatie",
    "take-away": "Afhaal",
    "group-order": "Groepsbestelling",
    "datetime": "Datum en tijd",
    "change-ordertype" : "Besteltype wijzigen?",
    "change-ordertype-desk" : "Besteltype wijzigen",
    "register-group-first" : "Nog niet geregistreerd als",
    "register-group-second" : "en interesse om te bestellen?",
    "contact-us" : "Contacteer ons",
    "company": "bedrijf,",
    "address": "Levering op adres",
    "on-invoice": "Op factuur",
    "group": "Groep",
    "at": "om",
    "delivery-fee":"Leverkosten",
    "tobe-paid": "Te betalen",
    "online-method": "Online",
    "class": "klas",
    "start-order-popup": "Start bestelling",
    "chose-group": "Kies uw groep",
    "intersted-ordering": "Interesse om als groep te bestellen?",
    "contact-promise": "Wij nemen zo snel mogelijk contact met u op.",
    "telephone-gsm": "Telefoon/GSM",
    "company-label": "Bedrijf",
    "city-label": "Gemeente",
    "send-message": "Bericht versturen",
    "message": "Bericht",
    "missing-fields-red": "Gelieve alle rood gekleurde velden in te vullen",
    "format-gsm": "Minimum 11 cijfers inclusief landcode. vb. +32488896655",
    "contact-success": "Bericht is succesvol verstuurd. Wij nemen zo snel mogelijk contact met u op.",
    "message-sent":"Bericht is succesvol verstuurd. Wij nemen zo snel mogelijk contact met u op.",
    "fill-all": "Gelieve alle velden in te vullen.",
    "in-house": "Ter plaatse",
    "monday": "Maandag",
    "tuesday": "Dinsdag",
    "wednesday": "Woensdag",
    "thursday": "Donderdag",
    "friday": "Vrijdag",
    "saturday": "Zaterdag",
    "sunday": "Zondag",
    "reserve" : "Reserveren",
    "menu-cart" : "Menukaart",
    "share" : "Deel",
    "loyalty-cart" : "Klantkaart",
    "house-number": "Huisnummer toevoegen",
    "choose-date": "Kies een datum",
    "date-time": "Datum & tijd",
    "choose-address-question" : "Op welk adres wenst u de bestelling te ontvangen?",
    "my-address" : "MIJN ADRES",
    "confirm" : "Bevestigen",
    "delete-confirmation" : "Bent u zeker dat u dit item wilt verwijderen?",
    "yes-remove" : "Ja, verwijder",
    "passed" : "Geslaagd!",
    "order-successfully" : "Uw bestelling werd succesvol verwerkt",
    "check-mail-order-successfully" : "Controleer uw inbox of spam mailbox voor een orderbevestiging en herinneringsmail",
    "back-to-assortment" : "Terug naar het assortiment",
    "back-to-login" : "Terug naar inloggen",
    "ordered-products" : "Bestelde artikelen",
    "Total" : "Totaal",
    "delivery-cost" : "Leverkosten",
    "details-of-order" : "Details van bestelling",
    "to-be-paid" : "Te betalen",
    "comment" : "Opmerking",
    "cash" : "Cash",
    "pay-cash" : "Cash betalen",
    "online" : "Online betalen",
    "unknown": "Te betalen",
    "pending": "Te betalen",
    "paid": "Betaald",
    "cancelled": "geannuleerd",
    "expired": "verlopen",
    "show_more": "Meer bekijken",
    "comlete-account-infor": "Vervolledig uw account",
    "enter-first-name-phone": "Vul de ontbrekende gegevens in om uw account te vervolledigen.",
    "account" : "Account",
    "choose-online-method": "Kies een online betaalmethode",
    "choose-online-method-desktop": "Kies een online betaalmethode naar keuze.",
    "cash-payment": "Ter plaatse",
    "cash-payment-delivery": "Aan de bezorger",
    "cash-payment-desktop": "Ter plaatse.",
    "cash-payment-desktop-delivery": "Aan de bezorger.",
    "receive-invoice": "Je ontvangt een factuur",
    "receive-invoice-desktop": "Ontvang een factuur en betaal achteraf.",
    "close-time": "bestel tot",
    "no-result": "Geen resultaten gevonden",
    "go-to": "Ga naar",
    "my-profile": "Mijn profiel",
    "save-address": "en sla uw adres op",
    "enter-infores": "Typ hier de naam van uw bedrijf, groep of klas",
    "email-fail": "Gelieve een geldig e-mailadres in te vullen.",
    'mobile-plus': "Telefoon/GSM",
    "receive-up-to": "Ontvang maximaal",
    "discount-next-order": "korting bij uw volgende besteling",
    "redeem": "Inwisselen",
    "adres": "Adres",
    "change-avatar": "Klik hieronder om uw profielfoto te wijzigen",
    "click-here": "Klik hier",
    "to-change-photo": "om uw profielfoto te wijzigen.",
    "check-mail-gift": "Een kopie van dit bericht is via e-mail verstuurd. Controleer uw mailbox.",
    "request-gift": "Vraag uw geschenk aan in het restaurant en laat dit bericht zien!",
    "redeemed": "Reeds ingewisseld",
    "credits-required": "credits nodig",
    "successful-redeem": "Succesvol ingewisseld",
    "auto-deducted-shopping-cart": "Uw klantenkaartkorting werd automatisch verrekend in uw winkelmandje",
    "applied-to-next-order": "Uw korting zal automatisch verrekend worden bij uw volgende bestelling.",
    "must-use-redeemed-discount": "Je hebt deze korting reeds ingewisseld! Plaats een bestelling en maak gebruik van deze korting!",
    "with-out": "Zonder ",
    "home-bottom1": "Ontdek ons assortiment →",
    "home-bottom2": "Start uw bestelling",
    "opps": "Oeps..",
    "edit-date": "Wijzig dag",
    "edit-time": "Wijzig tijd",
    "group-ordering": "Bestelling voor",
    "remove-products": "Verwijder producten",
    "unavailable-products": "Producten aangeduid in het rood zijn niet beschikbaar.",
    "not-delivery-products": "Producten aangeduid in het rood zijn niet beschikbaar voor levering. ",
    "invalidate-date" : "Een of meerdere artikelen zijn niet beschikbaar op de door u gekozen dag. Kies een andere dag of verwijder de rood gekleurde artikelen uit uw winkelmand.",
    "invalidate-time" : "Een of meerdere artikelen zijn niet beschikbaar op het door u gewenste uur. Kies een ander tijdslot of verwijder de rood gekleurde artikelen uit uw winkelmand.",
    "customer_card" : "Klantenkaart",
    "edit-profile-successfully" : "Uw profiel is succesvol gewijzigd",
    "unavailable-for-delivery" : "Één of meer producten zijn niet beschikbaar voor levering",
    "other-register" : "Of registreren met",
    "and" : "en",
    "active-account" : "Uw account is geactiveerd en klaar voor gebruik!",
    "start-order-desk" : "Maak een keuze uit het menu om uw bestelling te starten.",
    "searching-input" : "Zoeken naar producten",
    "email-confirmation": "E-mailadres bevestigen",
    "weekName": 'Zondag, Maandag, Dinsdag, Woensdag, Donderdag, Vrijdag, Zaterdag',
    "order-type-label": "Afhaal, Levering, Groepsvolgorde",
    "order-text": "bestelling",
    "order-text-empty": "Geen recente bestellingen beschikbaar",
    "sort-by-price-desk-decen" : "Prijs (AFLOPEND)",
    "sort-by-price-desk-acen" : "Prijs (OPLOPEND)",
    "day-name": "Vandaag",
    "day-name-continue": "dag geleden",
    "week-name": "week geleden",
    "contact": "Contact",
    "contact-description": "Vul onderstaande gegevens in indien u wenst te bestellen als bedrijf, groep of klas. Wij nemen spoedig contact met u op!",
    "back-contact": "Terug naar bestellen",
    "submit-contact": "Verzenden",
    "title-success-contact": "Bericht verstuurd",
    "description-success-contact": "Bericht is succesvol verstuurd. Wij nemen zo snel mogelijk contact met u op.",
    "continue-desk": "VERDER MET BESTELLEN",
    "notification-empty": "Geen berichten beschikbaar",
    "notification-read-all": "Markeer alle als gelezen",
    "days-name-continue": "Dagen geleden",
    "table-ordering-notfound-title": "Er is een probleem opgetreden.",
    "table-ordering-notfound-description": "Er doet zich een probleem voor. Je meldt dit best aan de handelaar.",
    "table-ordering-notfound-disable-title": "Momenteel gesloten",
    "table-ordering-notfound-disable-description": "Helaas, momenteel zijn we gesloten. We zien je graag terug tijdens onze openingsuren of probeer opnieuw.",
    "table-ordering-notfound-button": "Opnieuw proberen",
    "another address": "Een ander adres",
    "contact-gsm": "Mobiel telefoonnummer",
    "step2_title_cart": "Tafelnummer",
    "step2_text1": "Geef het telefoonnummer op van je mobiel toestel. Je ontvangt een SMS op dit nummer wanneer je bestelling klaar is.",
    "step2_text2": "U ontvangt uw kassabon via e-mail.",
    "step2_button": "Verder",
    "step2_email": "E-mailadres (optioneel)",
    "status_closed": "Gesloten",
    "status_about_to_close": "Gaat zo sluiten",
    "status_open": "Open",
    "choose-another-location": "levert niet op deze locatie. Kies een andere locatie of ga terug en kies voor afhaal.",
    "enter-delivery": "Vul hier uw gewenst leveradres in.",
    "invalid-coupon-desk" : "Deze code is niet correct.",
    "lastest": "laatste",
    "complete": "compleet.",
    "not": "niet",
    "not-complete": "niet compleet.",
    "step3-1-1" : "Ik ben de",
    "step3-1-2" : "Ik ben",
    "step3-2" : "en bevestig daarmee de bestelling van deze tafel als",
    "step3-3" : "de laatste en markeer de bestelling van deze tafel als",
    "check-request-gift-email": "Vraag uw geschenk aan in het restaurant. Een kopie van dit bericht is via e-mail verstuurd. Controleer uw mailbox.",
    "thank-you-for-order" : "Bedankt voor uw bestelling",
    "ship-asap" : "Uw bestelling is verzonden en komt er zo snel mogelijk aan.",
    "ship-asap-and-keep-phone" : "Uw bestelling is verzonden en komt er zo snel mogelijk aan. Houd zeker je telefoon bij de hand, je ontvangt een melding als je bestelling kan afgehaald worden.",
    "problem-occurred" : "Er is een probleem opgetreden.",
    "problem-occurred-and-report" : "Er doet zich een probleem voor. Je meldt dit best aan de handelaar.",
    "try-again" : "Opnieuw proberen",
    "currently-closed" : "Momenteel gesloten",
    "closed-order-again" : "Helaas, momenteel zijn we gesloten. We zien je graag terug tijdens onze openingsuren of probeer opnieuw.",
    "footer-desktop": "2024 © It’s Ready - algemene voorwaarden - privacyverklaring",
    "footer-copyright": "2024 © It’s Ready",
    "footer-terms": "algemene voorwaarden",
    "footer-privacy": "privacyverklaring",
    "table-ordering-step2-mess-number": "Error message.",
    "table-ordering-step2-mess-phone": "Minimum 11 cijfers inclusief landcode. bv. +32488896655",
    "table-ordering-step2-mess-email": "Gelieve een geldig e-mailadres in te vullen",
    "self-ordering-notfound-title": "Er is een probleem opgetreden.",
    "self-ordering-notfound-description": "Er doet zich een probleem voor. Je meldt dit best aan de handelaar.",
    "self-ordering-notfound-button": "Opnieuw proberen",
    "self-ordering-notfound-closed-title": "Momenteel gesloten",
    "self-ordering-notfound-closed-description": "Helaas, momenteel zijn we gesloten. We zien je graag terug tijdens onze openingsuren of probeer opnieuw.",
    "self-ordering-notfound-closed-button": "Opnieuw proberen",
    "step_confirmation": "Bevestiging",
    "search-portal": "Zoeken",
    "fill-postal-code": "Vul hier uw postcode in.",
    "man" : "Man",
    "woman" : "Vrouw",
    "en" : "en",
    "privacy-portal" : "privacybeleid",
    "sub-no-result" : "Wijzig je zoekcriteria of probeer opnieuw.",
    "page-not-found" : "Pagina niet gevonden",
    "order-ahead" : "Bestel vooruit",
    "profile-edit-success" : "Profiel succesvol bijgewerkt",
    "limit_time_to_payment" : "Helaas, bestellen voor het gewenste tijdstip is niet meer mogelijk. Kies een nieuw tijdstip.",
    "order_continuous" : "Verder met bestellen",
    "change_step_first_name_invalid": "Vul uw voornaam in om uw account te vervolledigen.",
    "change_step_phone_number_invalid": "Vul uw mobiel telefoonnummer in om uw account te vervolledigen.",
    "change_step_email_invalid": "Vul uw e-mailadres in om uw account te vervolledigen.",
    "change_step_common_invalid_format": "Vul de ontbrekende gegevens in om uw account te vervolledigen.",
    "lang_welcome_to_its_ready": "Welkom bij It’s Ready",
    "lang_login_of_account": "Log in of maak een account aan en bestel bij uw favoriete zaak!",
    "lang_of": "OF", 
    "lang_loading": "Loading",
    "lang_credits": "credits",
    "lang_not_found": "Page Not Found",
    "lang_could_not_found_resource": "Could not find the requested resource",
    "lang_something_went_wrong": "Something went wrong",
    "lang_try_again": "Try again",
    "lang_coupon_code": "Coupon Code",
    "lang_email_valid_message": "Ongeldig e-mailadres",
    "lang_sluiten": "SLUITEN",
    "lang_no_data": "No data",
    "lang_afaal": "AFHAAL",
    "lang_levering": "LEVERING",
    "lang_groepsbestelling": "GROEPSBESTELLING",
    "lang_min": "min",
    "lang_btw": "BTW",
    "lang_tel": "TEL",
    "lang_email_address": "E-mailadress",
    "lang_phone_valid_message": "Should contain a digit",
    "lang_email_form_label": "E-MAIL",
    "lang_gsm_form_label": "GSM",
    "lang_update_profile": "Update Profile",
    "lang_portal_lorem": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eut labore et dolore magna aliqua.",
    "lang_burger_stad": "Burger Stad",
    "lang_deluxe": "Deluxe hamburger met cheddarsaus",
    "lang_itsready_app": "It’s Ready app",
    "lang_account": "Account",
    "lang_profile_edit": "Profiel wijzigen",
    "lang_welcome_back": "Welkom terug",
    "lang_report": "Berichten",
    "lang_order_history": "Bestelgeschiedenis",
    "lang_logout": "Uitloggen",
    "lang_login": "Login",
    "lang_password_must_match": "passworden moeten overeenkomen",
    "security_invalid_description": "Scan nogmaals de QR-code & plaats je bestelling",
} as const
