export default {
    "search": "Zoeken",
    "free": "Gratis",
    "take-away" : "Afhalen",
    "choose-ordering-method": "Kies uw bestelwijze",
    "all": "Alles",
    "close": "Gesloten",
    "open": "Open",
    "sort-by": "Sorteren op",
    "name": "Naam",
    "default": "standaard",
    "handelaar": "Handelaar",
    "distance": "Afstand",
    "min-price": "Minimum bedrag",
    "delivery-cost": "Leveringskost",
    "min-wait-time": "Minimum wachttijd",
    "search-here": "Zoek op handelaar",
    "back-to-list": "Terug naar lijstweergave",
    "back-to-its": "Terug naar itsready.be",
    "terms-and-conditions": "Algemene voorwaarden",
    "my-account": "Mijn account",
    "home": "Home",
    "how-it-work": "Hoe werkt het",
    "find-merchants": "Zoek handelaars",
    "contact": "Contact",
    "enter-address": "Vul hier uw adres in",
    "search-by-merchant" : "Zoeken op handelaar",
    "merchants-with-loyalty" : "Toon enkel handelaars met een klantenkaart",
    "min-order-amount" : "Minimum bestelbedrag",
    "no-preference" : "Geen voorkeur",
    "or-less" : "of minder",
    "delivery-charge" : "Bezorgkosten",
    "register-trader" : "Aanmelden als handelaar",
    "new-traders" : "Nieuwe handelaars",
    "trader" : "Handelaar",
    "cookie-policy" : "Cookiebeleid",
    "filters" : "Filters",
    "opening" : "Nu geopend",
    "group-orders" : "Groepsbestellingen",
    "promoties" : "Promoties",
    "map-view" : "Mapweergave",
    "list-view" : "Lijstweergave",
    "no-result" : "Er zijn geen handelaars gevonden",
    "sub-no-result" : "Wijzig je zoekcriteria of probeer opnieuw.",
    "navigation" : "Navigatie",
    "find-dealer" : "Zoek een handelaar",
    "traders-website" : "Handelaars website",
    "craving-something" : "Goesting in iets",
    "tasty" : "lekkers",
    "home-placeholder" : "Postcode, stad of gemeente",
    "3-steps" : "Stil je honger in 3 stappen",
    "choose-trader" : "Kies uw favoriete handelaar",
    "sub-choose-trader" : "Zin in Grieks of op zoek naar een warme bakker? Uitgebreid diner of snelle snack? Het kan allemaal! Voer een locatie in en ontdek eetgelegenheden & handelaars bij jou in de buurt",
    "choose-payment" : "Kies uw betaalmethode",
    "sub-choose-payment" : "Vermijd lange wachtrijen en kies voor afhalen of levering op een vrij tijdstip naar keuze. Wens je liever te bestellen als bedrijf of klas? Vraag snel & eenvoudig je groepsaccount aan. Elk groepslid betaalt individueel via app of web.",
    "download-app" : "Download de",
    "sub-download-app" : "Bestel al het lekkers rechtstreeks via je telefoon en geniet van talloze voordelen",
    "dishes-at-hand" : "Je favoriete gerechten altijd bij de hand",
    "loyalty-merchants-together" : "Alle klantenkaarten van je favoriete handelaars samen",
    "promotions-and-offers" : "Blijf op de hoogte van promoties en aanbiedingen",
    "save-points" : "Plaats je bestelling & spaar punten",
    "sub-save-points" : "Kies uit het menu of maak gebruik van je bestelgeschiedenis en betaal eenvoudig online, cash of contactloos. Ook geen gedoe meer met klantenkaarten! Spaar zorgenloos voor leuke beloningen, want wij houden alle punten voor je bij",
    "cookie-message" : "We gebruiken cookies om u de beste ervaring op onze website te geven. Meer informatie vindt u in het",
    "cookie-message-link" : "cookiebeleid",
    "contact-with-us" : "Kom met ons in contact",
    "typy-here-first-name" : "Typ hier je voornaam",
    "typy-here-last-name" : "Typ hier je naam",
    "typy-here-email" : "Typ hier je e-mailadres",
    "typy-here-message" : "Vul hier je vraag of opmerking in.",
    "typy-here-phone" : "Typ hier je telefoonnummer",
    "sub-contact-success" : "Wij doen er alles aan om u zo snel mogelijk te woord te staan!",
    "sub-contact-with-email" : "Fout opgemerkt of een vraag voor ons?  Laat het ons weten en we helpen je zo snel mogelijk verder.  Je kan ons ook altijd contacteren op het e-mailadres  ",
} as const