import { useDimensions } from '@react-native-community/hooks';
import { IS_ANDROID } from '@src/configs/constants';
import {
    getStatusBarHeight,
    isIPhoneXx,
} from '@src/utils/iPhoneXHelper';
import {
    fontScale,
    horizontalScale,
    radiusScale,
    verticalScale,
} from '@src/utils/sizeScaling';
import { useMemo } from 'react';

export type DimensType = {
    W_0: number,
    W_1: number,
    W_2: number,
    W_3: number,
    W_4: number,
    W_5: number,
    W_6: number,
    W_7: number,
    W_8: number,
    W_9: number,
    W_10: number,
    W_11: number,
    W_12: number,
    W_13: number,
    W_14: number,
    W_15: number,
    W_16: number,
    W_17: number,
    W_18: number,
    W_19: number,
    W_20: number,
    W_21: number,
    W_22: number,
    W_23: number,
    W_24: number,
    W_25: number,
    W_26: number,
    W_27: number,
    W_28: number,
    W_29: number,
    W_30: number,
    W_31: number,
    W_32: number,
    W_33: number,
    W_34: number,
    W_35: number,
    W_36: number,
    W_37: number,
    W_38: number,
    W_39: number,
    W_40: number,
    W_41: number,
    W_42: number,
    W_43: number,
    W_44: number,
    W_45: number,
    W_46: number,
    W_47: number,
    W_48: number,
    W_49: number,
    W_50: number,
    W_51: number,
    W_52: number,
    W_53: number,
    W_54: number,
    W_55: number,
    W_56: number,
    W_57: number,
    W_58: number,
    W_59: number,
    W_60: number,
    W_61: number,
    W_62: number,
    W_63: number,
    W_64: number,
    W_65: number,
    W_66: number,
    W_67: number,
    W_68: number,
    W_69: number,
    W_70: number,
    W_71: number,
    W_72: number,
    W_73: number,
    W_74: number,
    W_75: number,
    W_76: number,
    W_77: number,
    W_78: number,
    W_79: number,
    W_80: number,
    W_81: number,
    W_82: number,
    W_83: number,
    W_84: number,
    W_85: number,
    W_86: number,
    W_87: number,
    W_88: number,
    W_89: number,
    W_90: number,
    W_91: number,
    W_92: number,
    W_93: number,
    W_94: number,
    W_95: number,
    W_96: number,
    W_97: number,
    W_98: number,
    W_99: number,
    W_100:number,
    W_110:number,
    W_120:number,
    W_124:number,
    W_127:number,
    W_128:number,
    W_130:number,
    W_138:number,
    W_140:number,
    W_144:number,
    W_150:number,
    W_160:number,
    W_180:number,
    W_186:number,
    W_199:number,
    W_200:number,
    W_206:number,
    W_216:number,
    W_220:number,
    W_999:number,

    H_0: number,
    H_1: number,
    H_2: number,
    H_3: number,
    H_4: number,
    H_5: number,
    H_6: number,
    H_7: number,
    H_8: number,
    H_9: number,
    H_10: number,
    H_11: number,
    H_12: number,
    H_13: number,
    H_14: number,
    H_15: number,
    H_16: number,
    H_17: number,
    H_18: number,
    H_19: number,
    H_20: number,
    H_21: number,
    H_22: number,
    H_23: number,
    H_24: number,
    H_25: number,
    H_26: number,
    H_27: number,
    H_28: number,
    H_29: number,
    H_30: number,
    H_31: number,
    H_32: number,
    H_33: number,
    H_34: number,
    H_35: number,
    H_36: number,
    H_37: number,
    H_38: number,
    H_39: number,
    H_40: number,
    H_41: number,
    H_42: number,
    H_43: number,
    H_44: number,
    H_45: number,
    H_46: number,
    H_47: number,
    H_48: number,
    H_49: number,
    H_50: number,
    H_51: number,
    H_52: number,
    H_53: number,
    H_54: number,
    H_55: number,
    H_56: number,
    H_57: number,
    H_58: number,
    H_59: number,
    H_60: number,
    H_61: number,
    H_62: number,
    H_63: number,
    H_64: number,
    H_65: number,
    H_66: number,
    H_67: number,
    H_68: number,
    H_69: number,
    H_70: number,
    H_71: number,
    H_72: number,
    H_73: number,
    H_74: number,
    H_75: number,
    H_76: number,
    H_77: number,
    H_78: number,
    H_79: number,
    H_80: number,
    H_81: number,
    H_82: number,
    H_83: number,
    H_84: number,
    H_85: number,
    H_86: number,
    H_87: number,
    H_88: number,
    H_89: number,
    H_90: number,
    H_91: number,
    H_92: number,
    H_93: number,
    H_94: number,
    H_95: number,
    H_96: number,
    H_97: number,
    H_98: number,
    H_99: number,
    H_100:number,
    H_106:number,
    H_110:number,
    H_120:number,
    H_124:number,
    H_127:number,
    H_128:number,
    H_130:number,
    H_138:number,
    H_140:number,
    H_144:number,
    H_150:number,
    H_160:number,
    H_180:number,
    H_186:number,
    H_199:number,
    H_200:number,
    H_206:number,
    H_216:number,
    H_220:number,
    H_999:number,

    FONT_30: number,
    FONT_28: number,
    FONT_26: number,
    FONT_24: number,
    FONT_23: number,
    FONT_22: number,
    FONT_21: number,
    FONT_20: number,
    FONT_18: number,
    FONT_16: number,
    FONT_15: number,
    FONT_14: number,
    FONT_13: number,
    FONT_12: number,
    FONT_11: number,
    FONT_10: number,
    FONT_9: number,
    FONT_8: number,

    RADIUS_2: number,
    RADIUS_3: number,
    RADIUS_4: number,
    RADIUS_6: number,
    RADIUS_8: number,
    RADIUS_10: number,
    RADIUS_12: number,
    RADIUS_14: number,
    RADIUS_16: number,
    RADIUS_18: number,
    RADIUS_20: number,
    RADIUS_22: number,
    RADIUS_24: number,
    RADIUS_26: number,
    RADIUS_28: number,
    RADIUS_30: number,
    RADIUS_32: number,
    RADIUS_999: number,

    COMMON_BOTTOM_PADDING: number,
    COMMON_HEADER_PADDING_EXTRA: number,
    COMMON_HEADER_PADDING: number,
    TAB_BAR_BOTTOM_PADDING: number,
    HEADER_BORDER_RADIUS: number,
    SCREEN_WIDTH: number,
    SCREEN_HEIGHT: number,
    DEFAULT_HIT_SLOP: {
        left: number,
        top: number,
        right: number,
        bottom: number,
    },
    DEFAULT_HIT_SLOP_SMALL: {
        left: number,
        top: number,
        right: number,
        bottom: number,
    },
}

const useDimens = (type = 'window'): DimensType => {
    const { screen, window  } = useDimensions();

    let width = window.width;
    let height = window.height;

    if (type === 'screen') {
        width = screen.width;
        height = screen.height;
    }

    const appDimens = useMemo(() => ({
        W_0: 0,
        W_1: horizontalScale(1, width),
        W_2: horizontalScale(2, width),
        W_3: horizontalScale(3, width),
        W_4: horizontalScale(4, width),
        W_5: horizontalScale(5, width),
        W_6: horizontalScale(6, width),
        W_7: horizontalScale(7, width),
        W_8: horizontalScale(8, width),
        W_9: horizontalScale(9, width),
        W_10: horizontalScale(10, width),
        W_11: horizontalScale(11, width),
        W_12: horizontalScale(12, width),
        W_13: horizontalScale(13, width),
        W_14: horizontalScale(14, width),
        W_15: horizontalScale(15, width),
        W_16: horizontalScale(16, width),
        W_17: horizontalScale(17, width),
        W_18: horizontalScale(18, width),
        W_19: horizontalScale(19, width),
        W_20: horizontalScale(20, width),
        W_21: horizontalScale(21, width),
        W_22: horizontalScale(22, width),
        W_23: horizontalScale(23, width),
        W_24: horizontalScale(24, width),
        W_25: horizontalScale(25, width),
        W_26: horizontalScale(26, width),
        W_27: horizontalScale(27, width),
        W_28: horizontalScale(28, width),
        W_29: horizontalScale(29, width),
        W_30: horizontalScale(30, width),
        W_31: horizontalScale(31, width),
        W_32: horizontalScale(32, width),
        W_33: horizontalScale(33, width),
        W_34: horizontalScale(34, width),
        W_35: horizontalScale(35, width),
        W_36: horizontalScale(36, width),
        W_37: horizontalScale(37, width),
        W_38: horizontalScale(38, width),
        W_39: horizontalScale(39, width),
        W_40: horizontalScale(40, width),
        W_41: horizontalScale(41, width),
        W_42: horizontalScale(42, width),
        W_43: horizontalScale(43, width),
        W_44: horizontalScale(44, width),
        W_45: horizontalScale(45, width),
        W_46: horizontalScale(46, width),
        W_47: horizontalScale(47, width),
        W_48: horizontalScale(48, width),
        W_49: horizontalScale(49, width),
        W_50: horizontalScale(50, width),
        W_51: horizontalScale(51, width),
        W_52: horizontalScale(52, width),
        W_53: horizontalScale(53, width),
        W_54: horizontalScale(54, width),
        W_55: horizontalScale(55, width),
        W_56: horizontalScale(56, width),
        W_57: horizontalScale(57, width),
        W_58: horizontalScale(58, width),
        W_59: horizontalScale(59, width),
        W_60: horizontalScale(60, width),
        W_61: horizontalScale(61, width),
        W_62: horizontalScale(62, width),
        W_63: horizontalScale(63, width),
        W_64: horizontalScale(64, width),
        W_65: horizontalScale(65, width),
        W_66: horizontalScale(66, width),
        W_67: horizontalScale(67, width),
        W_68: horizontalScale(68, width),
        W_69: horizontalScale(69, width),
        W_70: horizontalScale(70, width),
        W_71: horizontalScale(71, width),
        W_72: horizontalScale(72, width),
        W_73: horizontalScale(73, width),
        W_74: horizontalScale(74, width),
        W_75: horizontalScale(75, width),
        W_76: horizontalScale(76, width),
        W_77: horizontalScale(77, width),
        W_78: horizontalScale(78, width),
        W_79: horizontalScale(79, width),
        W_80: horizontalScale(80, width),
        W_81: horizontalScale(81, width),
        W_82: horizontalScale(82, width),
        W_83: horizontalScale(83, width),
        W_84: horizontalScale(84, width),
        W_85: horizontalScale(85, width),
        W_86: horizontalScale(86, width),
        W_87: horizontalScale(87, width),
        W_88: horizontalScale(88, width),
        W_89: horizontalScale(89, width),
        W_90: horizontalScale(90, width),
        W_91: horizontalScale(91, width),
        W_92: horizontalScale(92, width),
        W_93: horizontalScale(93, width),
        W_94: horizontalScale(94, width),
        W_95: horizontalScale(95, width),
        W_96: horizontalScale(96, width),
        W_97: horizontalScale(97, width),
        W_98: horizontalScale(98, width),
        W_99: horizontalScale(99, width),
        W_100: horizontalScale(100, width),
        W_110: horizontalScale(110, width),
        W_120: horizontalScale(120, width),
        W_124: horizontalScale(124, width),
        W_127: horizontalScale(127, width),
        W_128: horizontalScale(128, width),
        W_130: horizontalScale(130, width),
        W_138: horizontalScale(138, width),
        W_140: horizontalScale(140, width),
        W_144: horizontalScale(144, width),
        W_150: horizontalScale(150, width),
        W_160: horizontalScale(160, width),
        W_180: horizontalScale(180, width),
        W_186: horizontalScale(186, width),
        W_199: horizontalScale(199, width),
        W_200: horizontalScale(200, width),
        W_206: horizontalScale(206, width),
        W_216: horizontalScale(216, width),
        W_220: horizontalScale(220, width),
        W_999: horizontalScale(999, width),

        H_0: 0,
        H_1: verticalScale(1, height),
        H_2: verticalScale(2, height),
        H_3: verticalScale(3, height),
        H_4: verticalScale(4, height),
        H_5: verticalScale(5, height),
        H_6: verticalScale(6, height),
        H_7: verticalScale(7, height),
        H_8: verticalScale(8, height),
        H_9: verticalScale(9, height),
        H_10: verticalScale(10, height),
        H_11: verticalScale(11, height),
        H_12: verticalScale(12, height),
        H_13: verticalScale(13, height),
        H_14: verticalScale(14, height),
        H_15: verticalScale(15, height),
        H_16: verticalScale(16, height),
        H_17: verticalScale(17, height),
        H_18: verticalScale(18, height),
        H_19: verticalScale(19, height),
        H_20: verticalScale(20, height),
        H_21: verticalScale(21, height),
        H_22: verticalScale(22, height),
        H_23: verticalScale(23, height),
        H_24: verticalScale(24, height),
        H_25: verticalScale(25, height),
        H_26: verticalScale(26, height),
        H_27: verticalScale(27, height),
        H_28: verticalScale(28, height),
        H_29: verticalScale(29, height),
        H_30: verticalScale(30, height),
        H_31: verticalScale(31, height),
        H_32: verticalScale(32, height),
        H_33: verticalScale(33, height),
        H_34: verticalScale(34, height),
        H_35: verticalScale(35, height),
        H_36: verticalScale(36, height),
        H_37: verticalScale(37, height),
        H_38: verticalScale(38, height),
        H_39: verticalScale(39, height),
        H_40: verticalScale(40, height),
        H_41: verticalScale(41, height),
        H_42: verticalScale(42, height),
        H_43: verticalScale(43, height),
        H_44: verticalScale(44, height),
        H_45: verticalScale(45, height),
        H_46: verticalScale(46, height),
        H_47: verticalScale(47, height),
        H_48: verticalScale(48, height),
        H_49: verticalScale(49, height),
        H_50: verticalScale(50, height),
        H_51: verticalScale(51, height),
        H_52: verticalScale(52, height),
        H_53: verticalScale(53, height),
        H_54: verticalScale(54, height),
        H_55: verticalScale(55, height),
        H_56: verticalScale(56, height),
        H_57: verticalScale(57, height),
        H_58: verticalScale(58, height),
        H_59: verticalScale(59, height),
        H_60: verticalScale(60, height),
        H_61: verticalScale(61, height),
        H_62: verticalScale(62, height),
        H_63: verticalScale(63, height),
        H_64: verticalScale(64, height),
        H_65: verticalScale(65, height),
        H_66: verticalScale(66, height),
        H_67: verticalScale(67, height),
        H_68: verticalScale(68, height),
        H_69: verticalScale(69, height),
        H_70: verticalScale(70, height),
        H_71: verticalScale(71, height),
        H_72: verticalScale(72, height),
        H_73: verticalScale(73, height),
        H_74: verticalScale(74, height),
        H_75: verticalScale(75, height),
        H_76: verticalScale(76, height),
        H_77: verticalScale(77, height),
        H_78: verticalScale(78, height),
        H_79: verticalScale(79, height),
        H_80: verticalScale(80, height),
        H_81: verticalScale(81, height),
        H_82: verticalScale(82, height),
        H_83: verticalScale(83, height),
        H_84: verticalScale(84, height),
        H_85: verticalScale(85, height),
        H_86: verticalScale(86, height),
        H_87: verticalScale(87, height),
        H_88: verticalScale(88, height),
        H_89: verticalScale(89, height),
        H_90: verticalScale(90, height),
        H_91: verticalScale(91, height),
        H_92: verticalScale(92, height),
        H_93: verticalScale(93, height),
        H_94: verticalScale(94, height),
        H_95: verticalScale(95, height),
        H_96: verticalScale(96, height),
        H_97: verticalScale(97, height),
        H_98: verticalScale(98, height),
        H_99: verticalScale(99, height),
        H_100:verticalScale(100, height),
        H_106:verticalScale(106, height),
        H_110:verticalScale(110, height),
        H_120:verticalScale(120, height),
        H_124:verticalScale(124, height),
        H_127:verticalScale(127, height),
        H_128:verticalScale(128, height),
        H_130:verticalScale(130, height),
        H_138:verticalScale(138, height),
        H_140:verticalScale(140, height),
        H_144:verticalScale(144, height),
        H_150:verticalScale(150, height),
        H_160:verticalScale(160, height),
        H_180:verticalScale(180, height),
        H_186:verticalScale(186, height),
        H_199:verticalScale(199, height),
        H_200:verticalScale(200, height),
        H_206:verticalScale(206, height),
        H_216:verticalScale(216, height),
        H_220:verticalScale(220, height),
        H_999:verticalScale(999, height),

        FONT_30: fontScale(30, width, height),
        FONT_28: fontScale(28, width, height),
        FONT_26: fontScale(26, width, height),
        FONT_24: fontScale(24, width, height),
        FONT_23: fontScale(23, width, height),
        FONT_22: fontScale(22, width, height),
        FONT_21: fontScale(21, width, height),
        FONT_20: fontScale(20, width, height),
        FONT_18: fontScale(18, width, height),
        FONT_16: fontScale(16, width, height),
        FONT_15: fontScale(15, width, height),
        FONT_14: fontScale(14, width, height),
        FONT_13: fontScale(13, width, height),
        FONT_12: fontScale(12, width, height),
        FONT_11: fontScale(11, width, height),
        FONT_10: fontScale(10, width, height),
        FONT_9: fontScale(9, width, height),
        FONT_8: fontScale(8, width, height),

        RADIUS_2: radiusScale(2, width, height),
        RADIUS_3: radiusScale(3, width, height),
        RADIUS_4: radiusScale(4, width, height),
        RADIUS_6: radiusScale(6, width, height),
        RADIUS_8: radiusScale(8, width, height),
        RADIUS_10: radiusScale(10, width, height),
        RADIUS_12: radiusScale(12, width, height),
        RADIUS_14: radiusScale(14, width, height),
        RADIUS_16: radiusScale(16, width, height),
        RADIUS_18: radiusScale(18, width, height),
        RADIUS_20: radiusScale(20, width, height),
        RADIUS_22: radiusScale(22, width, height),
        RADIUS_24: radiusScale(24, width, height),
        RADIUS_26: radiusScale(26, width, height),
        RADIUS_28: radiusScale(28, width, height),
        RADIUS_30: radiusScale(30, width, height),
        RADIUS_32: radiusScale(32, width, height),
        RADIUS_999: radiusScale(999, width, height),

        SCREEN_WIDTH: width,
        SCREEN_HEIGHT: height,
        COMMON_BOTTOM_PADDING: IS_ANDROID || !isIPhoneXx() ? verticalScale(16, height) : verticalScale(24, height),
        COMMON_HEADER_PADDING_EXTRA: verticalScale(16, height),
        COMMON_HEADER_PADDING: verticalScale(getStatusBarHeight(), height) + verticalScale(16, height), // + COMMON_HEADER_PADDING_EXTRA
        TAB_BAR_BOTTOM_PADDING: IS_ANDROID || !isIPhoneXx() ? verticalScale(4, height) : verticalScale(24, height),
        HEADER_BORDER_RADIUS: verticalScale(8, height),
        DEFAULT_HIT_SLOP: {
            left: verticalScale(12, height),
            top: verticalScale(12, height),
            right: verticalScale(12, height),
            bottom: verticalScale(12, height),
        },
        DEFAULT_HIT_SLOP_SMALL: {
            left: verticalScale(4, height),
            top:verticalScale(4, height),
            right: verticalScale(4, height),
            bottom: verticalScale(4, height),
        }
    }), [height, width]);

    return appDimens;
};

export default useDimens;
