export default {
    "empty_cart": "Start your order by adding a product to your shopping cart.",
    "view_range": "View assortment",
    "subtotal": "Subtotal",
    "coupon_discount": "Coupon discount",
    "group_discount": "Group discount",
    "redeem_discount": "Loyalty card discount",
    "coupon_code": "Coupon code",
    "apply_redeem_discount": "Click here to apply your loyalty card discount",
    "apply_redeem_discount_desk": "Click here to use your loyalty card discount.",
    "total": "Total",
    "apply_coupon": "Apply",
    "comment": "Any comments",
    "further": "Next",
    "step_overview": "Order overview",
    "step_table_number": "Table number",
    "step_confirmation": "Confirmation",
    "step_payment_method": "Payment method",
    "product_added_success": "Product added to the shopping cart",
    "product_not_available": "Products marked in red are not available",
    "product_option_not_available": "Products and/or product options marked in red are not available",
    "message_invalid_coupon_product": "Discount is not applicable to the products in your cart.",
    "message_apply_coupon_successfully": "Coupon code applied successfully.",
    "message_apply_coupon_failed": "Please add a product to your cart first.",
    "oops": "Oops",
    "product_impossible_contact_admin": "It is not possible to add products to your cart. Please contact the operator.",
    "back": "Back",
    "delivery_free_from": "Free delivery from",
    "delivery_minimum": "{workspaceName} has a minimum order amount of: {price} excl. delivery costs",
    "delivery_minimum-desk": "{workspaceName} has a minimum order amount of: {price} excl. delivery costs",
    "delivery_costs": "Delivery costs",
    "delivery_not_shipping_1": "{workspaceName} does not deliver to this location.",
    "delivery_not_shipping_2": "Choose a",
    "delivery_not_shipping_3": "different location",
    "delivery_not_shipping_4": "or choose",
    "delivery_not_shipping_5": "pickup",
    "delivery_product_invalid": "Products marked in red are not available for delivery. Please remove them or choose pickup.",
    "delivery_product_not_sale": "Products marked in red are not available for this group.",
    "delivery_product_not_sale_pop": "One or more products are not available for this group.",
    "delivery_product_not_shipping": "One or more products are not available for delivery.",
    "desktop_empty_cart": "Make a choice from the menu to start your order.",
    "type_takeout_description": "Pickup at ",
    "type_delivery_description": "Your order delivered to an address of your choice.",
    "type_group_description": "Order with your company, group, or class.",
    "add": "Add",
    "facts": "Details",
    "type_not_active": "It is not possible to add products to your cart. Please contact the operator.",
    "group_inactive": "This group is no longer active. Please contact the operator.",
    "service_cost": "Servicekost",
    "service_cost_always_charge_on": "{workspaceName} hanteert een servicekost van {cost}",
    "service_cost_always_charge_off": "{workspaceName} hanteert een servicekost van {cost} tot een bestelbedrag van {price}",
} as const
