export default {
    "lang-value": "nl",
    "title": "Welcome to",
    "valid": "required",
    "optional": "Optional",
    "loading": "Loading...",
    "welcome": "Welcome to",
    "introduce": "Discover our menu and place your order to enjoy it on-site.",
    "introduce-self": "Discover our menu and place your order to take away.",
    "view-menu": "View our menu",
    "make-choice": "Make your choice",
    "enter-tb-number": "Enter your table number",
    "chose-payment": "Choose a payment method",
    "start-order": "START YOUR ORDER",
    "login": "Login",
    "login-nl": "Login",
    "log-in": "Log in",
    "login-title": "Log in or create an It's Ready account to order from your favorite place.",
    "sub-login-title-1": "Log in or create an",
    "sub-login-title-2": "It's Ready",
    "sub-login-title-3": "account and order from your favorite place",
    "login-with": "Login with",
    "forget-password": "Forgot password?",
    "register": "Don't have an account? \n Register here",
    "register-account": "Register",
    "register-btn": "Register",
    "missing-fields": "Please fill in all fields.",
    "first-name-contain-number": "Complete your account. The first field should be your first name.",
    "profile": "Profile",
    "change-profile": "Change profile",
    "more-information": "More information",
    "terms-and-conditions": "Terms and conditions",
    "privacy-policy": "Privacy policy",
    "cookie-policy": "Cookie policy",
    "privacy-policy-portal": "Privacy policy",
    "follow-on-facebook": "Follow on Facebook",
    "language": "Language",
    "login-or-register": "Login or register",
    "logout": "Logout",
    "nederlands": "Dutch",
    "english": "English",
    "frans": "French",
    "save": "Save",
    "no-cancel": "No, cancel",
    "yes-logout": "Yes, log out",
    "confirm-logout": "Are you sure you want to log out?",
    "shipping-fee": "Minimum shipping cost",
    "min-order": "Minimum order",
    "min-waiting": "Minimum wait time for delivery",
    "delivery": "Delivery",
    "its-ready": "It's Ready",
    "current-location": "Use current location",
    "recently-location": "Recently used locations",
    "my-location": "Use my address",
    "location": "Use location",
    "not-now": "Not now",
    "terms": "It's Ready © 2024",
    "label_new": "New",
    "home": "Home",
    "menu": "Menu",
    "shopping-cart": "Shopping cart",
    "not-available": "Not available",
    "no-items": "No items",
    "no-items-desk": "No items found in this category.",
    "nothing-at-all": "No items found",
    "nothing-at-all-desk": "No products found",
    "no-favorite-items": "No favorites found",
    "read_more": "Read more >",
    "show_less": "Show less",
    "full-name": "Full name",
    "apply": "Apply",
    "favorites": "Favorites",
    "required": "This field is required",
    "create-account": "Create your It's Ready account here to continue.",
    "create-account-1": "Create your",
    "create-account-2": "It's Ready",
    "create-account-3": "account here to continue.",
    "agree": "By creating this account, I agree to the",
    "term-condition": "terms and conditions",
    "reset-password-success-message": "Check your inbox or spam folder and follow the link to reset your password.",
    "invalid-email": "Enter a valid email address.",
    "email-sent": "Email sent",
    "fields-require": "This field is required.",
    "email-not-exist": "Your email address was not recognized. Please check your email address and try again.",
    "recover-title": "Recover password",
    "recover-subtitle": "Enter your email address to recover your password.",
    "change-password": "Change password",
    "enter-change-password": "Enter your new password.",
    "email-field": "Email address",
    "reset-password": "Reset password",
    "setup-password-title": "Set new password",
    "new-password": "New password",
    "repeat-password": "Repeat new password",
    "save-password": "Save password",
    "new-password-required": "Please enter a new password.",
    "password-min-length": "Please use at least 6 characters.",
    "repeat-password-required": "Please repeat your new password.",
    "password-not-match": "Passwords do not match.",
    "password-changed": "Password changed",
    "new-password-success": "Your new password has been successfully set.",
    "choose_at_least_option": "Please choose at least {number}",
    "register-almost": "Almost done",
    "register-check": "Check your inbox or spam folder and follow the link to activate your account.",
    "accpet-terms": "Please agree to the terms and conditions and privacy policy.",
    "first-name": "First name",
    "last-name": "Last name",
    "mobile": "Mobile phone number",
    "phone": "Phone number",
    "email": "Email address",
    "password": "Password",
    "password-confirm": "Confirm password",
    "enter-address": "Enter your address here",
    "format-email": "This email address was not recognized.",
    "stolen": "closed",
    "free": "FREE",
    "order-history": "Order history",
    "subtotal": "Subtotal",
    "coupon-discount": "Coupon discount",
    "redeem-discount": "Loyalty card discount",
    "group-discount": "Group discount",
    "total": "Total",
    "ordered-items": "Ordered items",
    "details-order": "Order details",
    "reorder": "Reorder",
    "payment-status": "Payment status",
    "payment-method": "Payment method",
    "comments": "Comments",
    "order-type": "Order type",
    "take-out": "Take-out",
    "coupon-1": "Go to your cart, enter this code, and get",
    "coupon-2": "discount on your order!",
    "coupon-3": "Enjoy",
    "coupon-4": "discount on any fries of your choice.",
    "coupon-5": "Go to your cart, enter this code, and get up to",
    "coupon-6": "discount on your order!",
    "go-shop": "Go to cart",
    "upload-avatar-success": "You have successfully changed the photo",
    "sort-by": "Sort by",
    "standard": "Standard",
    "sort-by-price": "Price (low to high)",
    "sort-by-name": "Name (A-Z)",
    "register-button": "Next",
    "register-portal": "Complete",
    "of": "OR",
    "register-with": "Register with",
    "vb": "e.g.: +32488893344",
    "failed": "Failed!",
    "invalid-link": "Oops.. The link is no longer valid.",
    "invalid-order": "OOPS... AN ERROR OCCURRED.",
    "invalid-desktop-title": "INVALID LINK",
    "invalid-table-desktop-description": "This website only supports mobile responsiveness.",
    "invalid-desktop-description": "The link you used is no longer valid. Please try again.",
    "invalid-desktop-button": "BACK TO SELECTION",
    "try-again-link": "The link you used is no longer valid. Please try again.",
    "try-again-order": "Your order was not completed correctly. Please check your payment method and try again.",
    "back": "Back",
    "fits": "This pairs well with it.",
    "no-thanks": "Continue with the order",
    "notification": "Messages",
    "close": "Close",
    "register-success": "Your account has been successfully created.",
    "account-created": "Account created",
    "ready": "Ready!",
    "on": "at",
    "am": "AM",
    "pm": "PM",
    "confirm-location": "Confirm location",
    "take-away": "Takeaway",
    "group-order": "Group order",
    "datetime": "Date and time",
    "change-ordertype": "Change order type?",
    "change-ordertype-desk": "Change order type",
    "register-group-first": "Not yet registered as",
    "register-group-second": "and interested in ordering?",
    "contact-us": "Contact us",
    "company": "Company",
    "address": "Delivery to address",
    "on-invoice": "On invoice",
    "group": "Group",
    "at": "at",
    "delivery-fee": "Delivery fee",
    "tobe-paid": "To be paid",
    "online-method": "Online",
    "class": "Class",
    "start-order-popup": "Start order",
    "chose-group": "Choose your group",
    "intersted-ordering": "Interested in ordering as a group?",
    "contact-promise": "We will contact you as soon as possible.",
    "telephone-gsm": "Phone/GSM",
    "company-label": "Company",
    "city-label": "City",
    "send-message": "Send message",
    "message": "Message",
    "missing-fields-red": "Please fill in all the red-marked fields",
    "format-gsm": "At least 11 digits including country code. e.g. +32488896655",
    "contact-success": "Message sent successfully. We will contact you as soon as possible.",
    "message-sent": "Message sent successfully. We will contact you as soon as possible.",
    "fill-all": "Please fill in all fields.",
    "in-house": "On-site",
    "monday": "Monday",
    "tuesday": "Tuesday",
    "wednesday": "Wednesday",
    "thursday": "Thursday",
    "friday": "Friday",
    "saturday": "Saturday",
    "sunday": "Sunday",
    "reserve": "Reserve",
    "menu-cart": "Menu",
    "share": "Share",
    "loyalty-cart": "Loyalty Card",
    "house-number": "Add house number",
    "choose-date": "Choose a date",
    "date-time": "Date & time",
    "choose-address-question": "Where would you like to receive your order?",
    "my-address": "MY ADDRESS",
    "confirm": "Confirm",
    "delete-confirmation": "Are you sure you want to delete this item?",
    "yes-remove": "Yes, delete",
    "passed": "Passed!",
    "order-successfully": "Your order was successfully processed",
    "check-mail-order-successfully": "Check your inbox or spam folder for an order confirmation and reminder email",
    "back-to-assortment": "Back to the assortment",
    "back-to-login": "Back to login",
    "ordered-products": "Ordered items",
    "Total": "Total",
    "delivery-cost": "Delivery costs",
    "details-of-order": "Order details",
    "to-be-paid": "To be paid",
    "comment": "Comment",
    "cash": "Cash",
    "pay-cash": "Pay by cash",
    "online": "Pay online",
    "unknown": "To be paid",
    "pending": "To be paid",
    "paid": "Paid",
    "cancelled": "Cancelled",
    "expired": "Expired",
    "show_more": "Show more",
    "comlete-account-infor": "Complete your account",
    "enter-first-name-phone": "Enter the missing data to complete your account.",
    "account": "Account",
    "choose-online-method": "Choose an online payment method",
    "choose-online-method-desktop": "Choose your preferred online payment method.",
    "cash-payment": "On-site",
    "cash-payment-delivery": "To the delivery person",
    "cash-payment-desktop": "On-site.",
    "cash-payment-desktop-delivery": "To the delivery person.",
    "receive-invoice": "You will receive an invoice",
    "receive-invoice-desktop": "Receive an invoice and pay later.",
    "close-time": "Order until",
    "no-result": "No results found",
    "go-to": "Go to",
    "my-profile": "My profile",
    "save-address": "and save your address",
    "enter-infores": "Enter the name of your company, group, or class here",
    "email-fail": "Please enter a valid email address.",
    "mobile-plus": "Phone/Mobile",
    "receive-up-to": "Receive up to",
    "discount-next-order": "discount on your next order",
    "redeem": "Redeem",
    "adres": "Address",
    "change-avatar": "Click below to change your profile picture",
    "click-here": "Click here",
    "to-change-photo": "to change your profile picture.",
    "check-mail-gift": "A copy of this message has been sent via email. Check your inbox.",
    "request-gift": "Request your gift at the restaurant and show this message!",
    "redeemed": "Already redeemed",
    "credits-required": "credits required",
    "successful-redeem": "Successfully redeemed",
    "auto-deducted-shopping-cart": "Your loyalty card discount was automatically applied to your shopping cart",
    "applied-to-next-order": "Your discount will be automatically applied to your next order.",
    "must-use-redeemed-discount": "You have already redeemed this discount! Place an order and use this discount!",
    "with-out": "Without ",
    "home-bottom1": "Explore our assortment →",
    "home-bottom2": "Start your order",
    "opps": "Oops..",
    "edit-date": "Change date",
    "edit-time": "Change time",
    "group-ordering": "Order for",
    "remove-products": "Remove products",
    "unavailable-products": "Products marked in red are not available.",
    "not-delivery-products": "Products marked in red are not available for delivery.",
    "invalidate-date": "One or more items are not available on the selected date. Choose another day or remove the red-marked items from your cart.",
    "invalidate-time": "One or more items are not available at the selected time. Choose another time slot or remove the red-marked items from your cart.",
    "customer_card": "loyalty card",
    "edit-profile-successfully": "Your profile was successfully updated",
    "unavailable-for-delivery": "One or more products are not available for delivery",
    "other-register": "Or register with",
    "and": "and",
    "active-account": "Your account has been activated and is ready to use!",
    "start-order-desk": "Choose from the menu to start your order.",
    "searching-input": "Search for products",
    "email-confirmation": "Confirm email address",
    "weekName": "Sunday, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday",
    "order-type-label": "Pick-up, Delivery, Group order",
    "order-text": "Order",
    "order-text-empty": "No recent orders available",
    "sort-by-price-desk-decen": "Price (Descending)",
    "sort-by-price-desk-acen": "Price (Ascending)",
    "day-name": "Today",
    "day-name-continue": "day ago",
    "week-name": "week ago",
    "contact": "Contact",
    "contact-description": "Fill in the details below if you wish to place an order as a business, group, or class. We will contact you shortly!",
    "back-contact": "Back to order",
    "submit-contact": "Submit",
    "title-success-contact": "Message sent",
    "description-success-contact": "Your message has been successfully sent. We will get back to you as soon as possible.",
    "continue-desk": "CONTINUE ORDERING",
    "notification-empty": "No messages available",
    "notification-read-all": "Mark all as read",
    "days-name-continue": "Days ago",
    "table-ordering-notfound-title": "There was an issue.",
    "table-ordering-notfound-description": "An issue occurred. You should report this to the merchant.",
    "table-ordering-notfound-disable-title": "Currently closed",
    "table-ordering-notfound-disable-description": "Unfortunately, we are currently closed. We look forward to seeing you during our opening hours or please try again.",
    "table-ordering-notfound-button": "Try again",
    "another address": "Another address",
    "contact-gsm": "Mobile phone number",
    "step2_title_cart": "Table number",
    "step2_text1": "Enter the phone number of your mobile device. You will receive an SMS on this number when your order is ready.",
    "step2_text2": "You will receive your receipt by email.",
    "step2_button": "Continue",
    "step2_email": "Email address (optional)",
    "status_closed": "Closed",
    "status_about_to_close": "Closing soon",
    "status_open": "Open",
    "choose-another-location": "does not deliver to this location. Choose another location or go back and select pickup.",
    "enter-delivery": "Enter your desired delivery address here.",
    "invalid-coupon-desk": "This code is incorrect.",
    "lastest": "latest",
    "complete": "complete.",
    "not": "not",
    "not-complete": "not complete.",
    "step3-1-1": "I am the",
    "step3-1-2": "I am",
    "step3-2": "and hereby confirm the order of this table as",
    "step3-3": "the last and mark the order of this table as",
    "check-request-gift-email": "Claim your gift at the restaurant. A copy of this message has been sent by email. Check your inbox.",
    "thank-you-for-order": "Thank you for your order",
    "ship-asap": "Your order has been shipped and will arrive as soon as possible.",
    "ship-asap-and-keep-phone": "Your order has been shipped and will arrive as soon as possible. Be sure to keep your phone on hand, as you will receive a notification when your order is ready for pickup.",
    "problem-occurred": "An issue occurred.",
    "problem-occurred-and-report": "An issue occurred. You should report this to the merchant.",
    "try-again": "Try again",
    "currently-closed": "Currently closed",
    "closed-order-again": "Unfortunately, we are currently closed. We look forward to seeing you during our opening hours or please try again.",
    "footer-desktop": "2024 © It’s Ready - Terms and Conditions - Privacy Policy",
    "footer-copyright": "2024 © It’s Ready",
    "footer-terms": "Terms and Conditions",
    "footer-privacy": "Privacy Policy",
    "table-ordering-step2-mess-number": "Error message.",
    "table-ordering-step2-mess-phone": "Minimum 11 digits including country code. e.g. +32488896655",
    "table-ordering-step2-mess-email": "Please enter a valid email address.",
    "self-ordering-notfound-title": "There was an issue.",
    "self-ordering-notfound-description": "An issue occurred. You should report this to the merchant.",
    "self-ordering-notfound-button": "Try again",
    "self-ordering-notfound-closed-title": "Currently closed",
    "self-ordering-notfound-closed-description": "Unfortunately, we are currently closed. We look forward to seeing you during our opening hours or please try again.",
    "self-ordering-notfound-closed-button": "Try again",
    "step_confirmation": "Confirmation",
    "search-portal": "Search",
    "fill-postal-code": "Enter your postal code here.",
    "man": "Man",
    "woman": "Woman",
    "en": "and",
    "privacy-portal": "Privacy Policy",
    "sub-no-result": "Modify your search criteria or try again.",
    "page-not-found": "Page not found",
    "order-ahead": "Order ahead",
    "profile-edit-success": "Profile successfully updated",
    "limit_time_to_payment": "Unfortunately, ordering for the desired time is no longer possible. Please select a new time.",
    "order_continuous": "Continue ordering",
    "change_step_first_name_invalid": "Enter your first name to complete your account.",
    "change_step_phone_number_invalid": "Enter your mobile phone number to complete your account.",
    "change_step_email_invalid": "Enter your email address to complete your account.",
    "change_step_common_invalid_format": "Enter the missing details to complete your account.",
    "lang_welcome_to_its_ready": "Welcome to It's Ready",
    "lang_login_of_account": "Log in or create an account and order from your favorite store!",
    "lang_of": "OR", 
    "lang_loading": "Loading",
    "lang_credits": "Credits",
    "lang_not_found": "Page Not Found",
    "lang_could_not_found_resource": "Could not find the requested resource",
    "lang_something_went_wrong": "Something went wrong",
    "lang_try_again": "Try again",
    "lang_coupon_code": "Coupon Code",
    "lang_email_valid_message": "Invalid email address",
    "lang_sluiten": "CLOSE",
    "lang_no_data": "No data",
    "lang_afaal": "PICKUP",
    "lang_levering": "DELIVERY",
    "lang_groepsbestelling": "GROUP ORDER",
    "lang_min": "min",
    "lang_btw": "VAT",
    "lang_tel": "TEL",
    "lang_email_address": "Email address",
    "lang_phone_valid_message": "Should contain a digit",
    "lang_email_form_label": "EMAIL",
    "lang_gsm_form_label": "Mobile",
    "lang_update_profile": "Update Profile",
    "lang_portal_lorem": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eut labore et dolore magna aliqua.",
    "lang_burger_stad": "Burger City",
    "lang_deluxe": "Deluxe hamburger with cheddar sauce",
    "lang_itsready_app": "It's Ready app",
    "lang_account": "Account",
    "lang_profile_edit": "Edit Profile",
    "lang_welcome_back": "Welcome back",
    "lang_report": "Reports",
    "lang_order_history": "Order history",
    "lang_logout": "Log out",
    "lang_login": "Login",
    "lang_password_must_match": "Passwords must match",
    "security_invalid_description": "Scan the QR code again and place your order",
} as const
