export default {
    "search": "Search",
    "free": "Free",
    "take-away" : "Take-away",
    "choose-ordering-method": "Choose your order type",
    "all": "All",
    "close": "Closed",
    "open": "Open",
    "sort-by": "Sort by",
    "name": "Name",
    "default": "Default",
    "handelaar": "Merchant",
    "distance": "Distance",
    "min-price": "Minimum amount",
    "delivery-cost": "Delivery cost",
    "min-wait-time": "Minimum wait time",
    "search-here": "Search by merchant",
    "back-to-list": "Back to list view",
    "back-to-its": "Back to itsready.be",
    "terms-and-conditions": "Terms and conditions",
    "my-account": "My account",
    "home": "Home",
    "how-it-work": "How it works",
    "find-merchants": "Find merchants",
    "contact": "Contact",
    "enter-address": "Enter your address here",
    "search-by-merchant" : "Search by merchant",
    "merchants-with-loyalty" : "Show only merchants with a loyalty card",
    "min-order-amount" : "Minimum order amount",
    "no-preference" : "No preference",
    "or-less" : "or less",
    "delivery-charge" : "Delivery charge",
    "register-trader" : "Register as a merchant",
    "new-traders" : "New merchants",
    "trader" : "Merchant",
    "cookie-policy" : "Cookie policy",
    "filters" : "Filters",
    "opening" : "Now open",
    "group-orders" : "Group orders",
    "promoties" : "Promotions",
    "map-view" : "Map view",
    "list-view" : "List view",
    "no-result" : "No merchants found",
    "sub-no-result" : "Change your search criteria or try again.",
    "navigation" : "Navigation",
    "find-dealer" : "Find a merchant",
    "traders-website" : "Merchant's website",
    "craving-something" : "Craving something",
    "tasty" : "Delicious",
    "home-placeholder" : "Postal code, city or municipality",
    "3-steps" : "Satisfy your hunger in 3 steps",
    "choose-trader" : "Choose your favorite merchant",
    "sub-choose-trader" : "Craving Greek or looking for a warm bakery? Full dinner or quick snack? It's all possible! Enter a location and discover restaurants & merchants near you.",
    "choose-payment" : "Choose your payment method",
    "sub-choose-payment" : "Avoid long lines and choose take-away or delivery at any time of your choice. Prefer to order as a business or class? Quickly and easily request your group account. Each group member pays individually via the app or web.",
    "download-app" : "Download the app",
    "sub-download-app" : "Order all the delicious food directly through your phone and enjoy numerous benefits",
    "dishes-at-hand" : "Your favorite dishes always at hand",
    "loyalty-merchants-together" : "All your favorite merchants' loyalty cards together",
    "promotions-and-offers" : "Stay updated on promotions and offers",
    "save-points" : "Place your order & collect points",
    "sub-save-points" : "Choose from the menu or use your order history and pay easily online, with cash, or contactless. No more hassle with loyalty cards! Collect points effortlessly for great rewards, as we keep track of all your points.",
    "cookie-message" : "We use cookies to provide you with the best experience on our website. More information can be found in the",
    "cookie-message-link" : "cookie policy",
    "contact-with-us" : "Contact us",
    "typy-here-first-name" : "Type your first name here",
    "typy-here-last-name" : "Type your last name here",
    "typy-here-email" : "Type your email here",
    "typy-here-message" : "Enter your question or comment here.",
    "typy-here-phone" : "Type your phone number here",
    "sub-contact-success" : "We will do our best to respond as soon as possible!",
    "sub-contact-with-email" : "Noticed a mistake or have a question for us? Let us know, and we will assist you as quickly as possible. You can always contact us at the email address",
} as const
